### ISSUE TITLE
[REQUEST] display system on designated axes

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#152]
optional argument ax=AXIS

when an AXIS is given to display system, it will display on that axis. In this case plt.show() should also be deactivated so that display system does not interfere with plotting on the other axes.

**Comment by OrtnerMichael** [comment]
make ComplexShape example program with 1 fig 2 axes where display system fills 2nd axis

**Comment by lucasgcb** [comment]
So we want this is for programatically tilting the display in order to focus on a particular axis?

**Comment by lucasgcb** [comment]
Here's two new kwargs for displaySystem for review:

- existingFig=None
  - This is figure data that already exists. displaySystem will create a subplot in this figure and plot the 3D inside of it.
- subplotArg=[1,2,2]
  - This is the subplot `nrows, ncols, and index` data. Enter it as a list.

```python
import numpy as np
import matplotlib.pyplot as plt
from magpylib.source.magnet import Box
from magpylib import Collection

#create collection of four magnets
s1 = Box(mag=[ 500,0, 500], dim=[3,3,3], pos=[ 0,0, 3], angle=45, axis=[0,1,0])
s2 = Box(mag=[-500,0,-500], dim=[3,3,3], pos=[ 0,0,-3], angle=45, axis=[0,1,0])
s3 = Box(mag=[ 500,0,-500], dim=[4,4,4], pos=[ 4,0, 0], angle=45, axis=[0,1,0])
s4 = Box(mag=[-500,0, 500], dim=[4,4,4], pos=[-4,0, 0], angle=45, axis=[0,1,0])
c = Collection(s1,s2,s3,s4)

#create positions
xs = np.linspace(-8,8,100)
zs = np.linspace(-6,6,100)
posis = [[x,0,z] for z in zs for x in xs]

#calculate fields
Bs = c.getBsweep(posis)

#reshape array and calculate amplitude
Bs = np.array(Bs).reshape([100,100,3])
Bamp = np.linalg.norm(Bs,axis=2)

##amplitude plot
X,Z = np.meshgrid(xs,zs)

##Define Figure
fig = plt.figure()

##Define subplot for 2D
ax1 = fig.add_subplot(1, 2, 1, axisbelow=True)
plt.contourf(X,Z,Bamp,100,cmap='rainbow')

##field plot 2D
U,V = Bs[:,:,0], Bs[:,:,2]
plt.streamplot(X, Z, U, V, color='k', density=2)

##Define suplot for 3D and plot Collection
c.displaySystem(externalFig=fig,subplotArg=[1,2,2])
```

![image](https://user-images.githubusercontent.com/7332704/58972249-684dab00-87bd-11e9-9bbb-0bfca941e973.png)
