### ISSUE TITLE
[REQUEST] Possibility of global magnetization

### ISSUE THREAD

**Issue by fslanovc** [magpylib/magpylib#199]
Since the magnetization direction is always set relative to the initial orientation, it is not trivial to change the magnetization direction to a certain global direction after rotations etc.

A method which is able to apply a global direction to objects might especially be useful for parallel alignment of a collection of multiple sources.

Maybe in form of a method like: setGlobalMagnetiztionDirection(unitVector)

edit: Current sources within a collection may not be affected by that.

**Comment by lucasgcb** [comment]
Hey, Flor! Thanks for the feedback :)

I can see the realization of this feature and how it would indeed save time if someone wanted to achieve this goal (calculating a new relative magnetization vector based on a desired absolute field vector, based on the current magnet orientation). 

Could you go into a little bit of detail for a use case where this sort of remagnetization would be useful, however? This would help a lot in taking the decision to invest on more features.

**Comment by fslanovc** [comment]
I was just thinking about one particular use case:
If you design a fairly complex system of magnetic material, one could investigate the behavior of the magnetic stray field as a function of the magnetization direction.
Perhaps I was thinking about that because my colleagues in Vienna are doing that 3D-printing stuff, so they design some magnetic configuration and align all magnetic moments in one direction by heating up and applying an external field afterwards (https://aip.scitation.org/doi/pdf/10.1063/1.4964856?class=pdf).

I really don't know if this is worth the effort, because you could also align it manually with a little bit of a priori calculation...this was just an idea for a possible additional feature! ;)
