### ISSUE TITLE
getPhi -> arctan2

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#221]
rename

careful with different Definition of arctan2(0,0)

why is getPhi faster than arctan2 ?

**Comment by OrtnerMichael** [comment]
`def getPhi(x, y):
    if x > 0:
        return arctan(y/x)
    elif x < 0:
        if y >= 0:
            return arctan(y/x)+pi
        else:
            return arctan(y/x)-pi
    else:
        if y > 0:
            return pi/2
        else:
            return -pi/2
        
x = 0
y = -.000001
#print(getPhi(x,y))
#print(arctan2(y,x))



T0 = time.perf_counter()
for _ in range(9999999):
    getPhi(-1,-2)
    arctan2(.2,-1)
T1 = time.perf_counter()
print(T1-T0)`

**Comment by Alexboiboi** [comment]
> why is getPhi faster than arctan2

This is only True if values are passed directly. As soon as you want to pass arrays it delivers drastically different results. The advantage of numpy's `arctan2` is the ability to pass arrays efficiently.

Here some comparison results ;)


```python
from numpy import arctan, arctan2, pi, random, array
import timeit
import plotly.graph_objects as go

def getPhi(x, y):
    if x > 0:
        return arctan(y/x)
    elif x < 0:
        if y >= 0:
            return arctan(y/x)+pi
        else:
            return arctan(y/x)-pi
    else:
        if y > 0:
            return pi/2
        else:
            return -pi/2       
N=100
X = random.randn(N)
Y = random.randn(N)

ar = []
def getPhi_array(X,Y):
    for x,y in zip(X,Y):
        ar.append(getPhi(x,y))
    return array(ar)
```

```python
%%timeit 
getPhi(0, -.000001)
```
409 ns ± 39.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

```python
%%timeit
arctan2( -.000001,0)
```
2.16 µs ± 46.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

```python
%%timeit 
getPhi(X[0],Y[0])
```
3.33 µs ± 38.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

```python
%%timeit
arctan2(Y[0],X[0])
```
4.02 µs ± 174 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


And here with varying array size:

```python
setup = '''
from numpy import arctan, arctan2, pi, random, array

def getPhi(x, y):
    if x > 0:
        return arctan(y/x)
    elif x < 0:
        if y >= 0:
            return arctan(y/x)+pi
        else:
            return arctan(y/x)-pi
    else:
        if y > 0:
            return pi/2
        else:
            return -pi/2       

X = random.randn(N)
Y = random.randn(N)

ar = []
def getPhi_array(X,Y):
    for x,y in zip(X,Y):
        ar.append(getPhi(x,y))
    return array(ar)
    
'''

```

```python
a = []
b = []
num = range(1,100,10)
for n in num:
    number = 1000
    a.append(timeit.timeit(stmt='getPhi_array(X,Y)', 
                           setup=setup, number=number, 
                           globals=dict(N=n))
             /number*1000)
    b.append(timeit.timeit(stmt='arctan2(Y,X)', 
                           setup=setup, 
                           number=number, 
                           globals=dict(N=n))/number*1000)
fig = go.Figure()
fig.update_layout(xaxis_title='Number of elements', 
                  yaxis_title='time [ms]', 
                  yaxis_type='log')
fig.add_scatter(x=list(num), y=a, name='getPhi')
fig.add_scatter(x=list(num), y=b, name='arctan2 numpy')
```
![Capture](https://user-images.githubusercontent.com/29252289/67237026-b8669a80-f44a-11e9-9de3-1ea553c5184c.PNG)

**Comment by OrtnerMichael** [comment]
hmm, das ist aber kein fairer vergleich mit dem loop da oben :)

versuch mal:
arctan(Y/X) - (sign(X)-1)*sign(Y)*pi/4
wobei Y und X numpy arrays sind

**Comment by OrtnerMichael** [comment]
in dem Fall 
myAtan2 = arctan(Y/X) - (sign(X)-1)*sign(Y)*pi/4 

ist myAtan2 ein bisschen schneller als np.atan2, nicht relevant, warscheinlich weil in atan2 noch eine 0-abfrage und entsprechende fall selektion drin ist.
