### ISSUE TITLE
[BUG] - Catch Special Cases in Vectorized Code

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#243]
![image](https://user-images.githubusercontent.com/47384012/77907044-4744d200-7289-11ea-89a2-6809de89635f.png)

**Comment by OrtnerMichael** [comment]
why do we get 0-division here ? ... oviously outside of the magnet compound

**Comment by zflansberry** [comment]
Hi @OrtnerMichael , I did analyze that particular problem. When two of the coordinates of the measurement are equal to two of the coordinates of the box corners (i.e. measurement at (1, 1, 10) for a box of dimensions (2, 2, 2) centered at (0, 0, 0)), two of the terms in the log will become zero and you get a log(0/0) indeterminate form. Analytically, both terms cancel each other out but I'm not sure how to integrate that cleanly in the code.

My quick fix was to perturb the position of those special cases in `PM_Box_vector()`:
#
    xma, xpa = x-a, x+a
    ymb, ypb = y-b, y+b
    zmc, zpc = z-c, z+c

    # Find special cases and perturb their positions (need two coords aligned with coords of corner of block)
    sc = np.where(np.sum(
        np.isclose(np.c_[xma, xpa, ymb, ypb, zmc, zpc], 0.0, 1e-5), axis=1) >= 2)[0]
    if sc.size:
        pb = POS[sc].max(axis=1)/1e4     # Perturbation is 1e-4 of distance
        xma[sc] +=  pb   
        xpa[sc] +=  pb   # Works out better if all pertbs have same sign
        ymb[sc] +=  pb
        ypb[sc] +=  pb
        zmc[sc] +=  pb
        zpc[sc] +=  pb
        del pb
    del sc
# 

Definitely not a perfect solution as it is not an analytic solution anymore at those specific points.

**Comment by OrtnerMichael** [comment]
Hi @zflansberry 
Thank you for the suggestion. You are right about the problem.

In PM_Box the special cases (where Log(0/0) happens are caught, but in PM_Box_vector they are not. As you also point out the pertubation is not a good solution as it will falsify results when it comes to high precision computations.

One should implement the equations in the proper limit instead as is done in PM_box.

The original thought was that catching the special cases reduces performance, but this problem breaks a lot of codes like optimization algorithms so I guess one really has to look into it.
