### ISSUE TITLE
[REQUEST] Making custom child classes more compatible with the library

### ISSUE THREAD

**Issue by rodsrodolfo** [magpylib/magpylib#248]
I'm heaving a hard time creating child classes from Cylinder and Box and getting the methods to work.

I'm trying to simulate some magnet assembles and the magnets I use are always the same (for example a cylinder with dimensions dim=[15,100] and magnetization mag=[0, 0, 1170]). What I tried to do is create a custom class which is a child from the Cylinder class to store those constant values and only specify pos, angle, etc when making an instance.

Initializing the class with the parents initialization or super() and using methods like getB works, but putting an instance of this custom class inside a Collection is not always smooth, as methods from Collection like displaySystem check the collection's instances types before doing anything with it. The custom class then fails the type check and are not considered to be in the collection.

My only workaround was modifying the very magpylib's code. Or create a custom class only to store those values and then making an instance of Cylinder with mag=custommagnet.mag as a parameter, which is not ideal nor clean.

I'd love to hear if I'm doing this wrong and if changing those type checks is possible.

**Comment by OrtnerMichael** [comment]
Hi, 
sorry for the late reply.
You make a custom class to avoid having the arguments (dim=DIM, mag=MAG for some fixed values of DIM and MAG) all over the code ?
Why not just use the same object and adjust the parameters to your liking ?

Can you explain what is the goal of your computation ?

sincerely,
Michael

**Comment by rodsrodolfo** [comment]
Hello,

Indeed the intention is to avoid repeating those arguments. The goal is to
have for example a .py with pre defined magnets available from a database,
which would be child classes from the magpylib magnets, and use them in
simulations, thus allowing me to create 2 or more instances of those pre
defined magnets in a magnet arrangement.

I couldn't use the same object to create 2 instances of the same magnet in
different positions. Moving the "copy" instance would also move the
original one. If this is not the expected behaviour, I could have missed
something.

My problems with the parent classes is that not all methods work, because
some of them run type tests, and as the parent class does not generate an
instance that passes the type check, the method doesn't work.

Thanks for the reply,

Mateus

**Comment by OrtnerMichael** [comment]
I understand your problem, ty for pointing it out.

I'm not really sure at this point how to circumvent it, but we will keep this suggesttion in the list of problems to be solved and try to figure it out.

Any suggestions welcome :)

sincerely,
michael

**Comment by traavnik** [comment]
@rodsrodolfo have you considered using a [copy ](https://docs.python.org/3/library/copy.html) function? From your description it seems that you used object assignment:
`s1 = Box(mag=(0,0,600), dim=(3,3,3), pos=(-4,0,3))`
`s2 = s1`
instead of making a true copy:
`import copy`
`s1 = Box(mag=(0,0,600), dim=(3,3,3), pos=(-4,0,3))`
`s2 = copy.copy(s1)`

I'm sorry if I misunderstood your problem.

**Comment by rodsrodolfo** [comment]
Hello,

Thanks for pointing this option out, I had indeed not thought of it.

Mateus

Em qui., 3 de set. de 2020 às 16:16, traavnik <notifications@github.com>
escreveu:

**Comment by OrtnerMichael** [comment]
Thank you for the feedback @traavnik  and @rodsrodolfo I'm closing this issue. Be sure to check out the new version 3.0.0 in a few weeks (development3 brach is already installable)
