### ISSUE TITLE
[REQUEST] Example for magnet defined by facet

### ISSUE THREAD

**Issue by raulmd** [magpylib/magpylib#251]
**Is your feature request related to some problem? If yes, please describe.**
Want to simulate a magnet shape as an extruded trapezoid. Seems that it could be defined by the [facet](https://magpylib.readthedocs.io/en/latest/_autogen/magpylib.source.magnet/#magpylib.source.magnet.Facet), but in the documentation can not find an example.
![image](https://user-images.githubusercontent.com/6444633/95891924-553aea00-0db8-11eb-9f89-0fb5c2f61ba4.png)

**Describe the feature you'd like**
Basic example

**Describe alternatives or solutions you've considered**
there is no superposition I can imagine that will make this work.

**Comment by OrtnerMichael** [comment]
Hello raulmd,
Sorry for the late reply ! We will add a facet example as soon as possible - unfortunately the original code was broken (its currently not working) but will be integrated again with Version 1.0.0 expected at the end of this year / beginning of January
