### ISSUE TITLE
[REQUEST] Add Arc as a new current source

### ISSUE THREAD

**Issue by ReciprocalSpace** [magpylib/magpylib#253]
Hey,

I love your library and this paper came out three days ago : 

M. A. Gonzalez et al. "Analytical expressions for the magnetic field generated by a circular arc filament carrying a direct current" in a IEEE journal. 

An "Arc" current source class would come very handy and I think it would be a wonderful addition to Magpylib ! 

 [09293274.pdf](https://github.com/magpylib/magpylib/files/5708529/09293274.pdf)

Regards,
Aimé Labbé

**Comment by laikh** [comment]
Hi thanks for the suggestion.
We are working on a major update, to be expected at the end of january and will include this new source !

sincerely,
michael
