### ISSUE TITLE
[Question] Calculating gradient and curvature of the field.

### ISSUE THREAD

**Issue by linhz0hz** [magpylib/magpylib#257]
In the applications I use, I want to calculate the gradient and curvature of the B field on top of the bias field. It will be nice to have these features calculated analytically.

I would like to implement it, but this is my first time implementing big libraries, so some suggestings/guidance would be appreciated.

**Comment by laikh** [comment]
hi,

Well there are two ways. You can use magpylib and implement gradient and
curvature using finite differences. That does not sound too hard and will
probably take you one day :). Be sure to follow the criterias of the
gradient/Jacobian matrix implemented in scipy.

Analytical derivations of the fields sounds more interesting, however the
derivatives are not so easy to obtain in many cases...a numerically solid
implementation can take quite a while.

sincerely,
michael

**Comment by OrtnerMichael** [comment]
hi again,
I think I have misundestood your propsition. You want to help to implement it in magpylib ?

At this point we have not thought to provide gradient fields, however, analytical formulas to gradient fields would be extremely welcome. Do you already have solutions /literature/an implementation ?

We have also not thought about how the gradient field could be integrated into the package. Do you have a suggestion ?

sincerely,
michael

**Comment by linhz0hz** [comment]
> hi again,
> I think I have misundestood your propsition. You want to help to implement it in magpylib ?
> 
> At this point we have not thought to provide gradient fields, however, analytical formulas to gradient fields would be extremely welcome. Do you already have solutions /literature/an implementation ?
> 
> We have also not thought about how the gradient field could be integrated into the package. Do you have a suggestion ?
> 
> sincerely,
> michael

This is my original intention.
I have some formula for simple line current I am using for a project. These are derived simply by differentiating the Biot-Savart law. For circle and dipolar field I suspect I can do similar things. But for permanent magnet block, I am not sure if you have a good reference to the analytical expression, and how easy it is to differentiate them. Maybe it helps to document those formulas first?

**Comment by OrtnerMichael** [comment]
dear @linhz0hz ,
sorry for the late reply. at this point we do not know how we would integrate the field derivatives into the package. Please let us know if you have a good idea (interface-wise) or a specific use-case in mind.

Concerning your questions to state-of-the-art formulas: There are several references to scientific papers in the documentation, and in the new version (branch magpylib3_development) in the field computation files there is a documentation of which papers were used for the respective implemenations.

**Comment by OrtnerMichael** [comment]
Hi @linhz0hz 

This sounds like a great project !

You are completely correct that the formulas implementd in Magplyib assume perfect homogenous magnetizations. There are two reasons why this is a problem:

1. Demagnetization effects: This refers to a change of the magnetization according to the material law (Hysteresis loops). As a result the magnetization is reduced in amplitude AND becomes inhomogeneous. With high grade NdFeB or SmCo materials with low mu_r (<1.05) you will see ~1% reduced field amplitude and much less qualitative change of the field (the farther away the better). This is expressed in the last part of the Appendix of the following paper:

https://www.mdpi.com/1424-8220/20/23/6873

You can compute demagnetization by using a FEM environment, however, be warned when using the only available freeware magnetic FEM program called FEMM, that it only computes effective 2D solutions. The error will be much larger than the Magpylib approximation when using good materials.

https://www.femm.info/wiki/HomePage

2. The magnets that you get from manufacturers typically show a few degrees of angle error of the magnetization and easily up to 10% wrong magnetic field amplitude when compared to the data sheet.

Problem 2 is much more severe than problem 1. This means that even if you can use Magpylib to compute the field of a Halbach array fitting to you NMR application, the magnets you are bying will not fulfill your precision requirements. I fear there is no way to get around shimming. 

I would use Magpylib to design a Halbach array, dont worry about demagnetization effects, and then use a shimming mechanism to make the field as homogenous as possible.

We have now also created a new Issue-category "Questions on Magnetics". If you have any more questions please feel free to drop us a line :).

sincerely,
michael

**Comment by linhz0hz** [comment]
Thanks!

I basically reached the same conclusion in the end last time I tried this. I was able to get 0.4T with a budget of a few hundred dollars. In the design phase I did not find a good supplier specification of these errors and in the end the homogeneity is probably too bad that I could not see a signal, probably due to under-estimation of these errors. Now I have graduated from my undergraduate institution and moved on to other projects which also requires some shimming. It might take a while for me or soemone else to continue and make this original NMR project work, but yes it is a good project!

If it is valuable, I could adapt some of my previous code to use magpylib and make that an example.

Also, just for fun, here are some picutures of the previous attempt for a halbach array by me and some of my friends.

![halbach_array_product](https://user-images.githubusercontent.com/40478937/110836970-b46d2f80-826e-11eb-9c17-3344d4be221a.jpg)
![B_mag_ideal_labelled](https://user-images.githubusercontent.com/40478937/110838034-fea2e080-826f-11eb-8f79-eff8895054d1.png)

**Comment by OrtnerMichael** [comment]
dear @linhz0hz 

This looks very cool. If you put a pdf together i would gladly upload it to the documentation webpage as an example. The example section will be create with the new Magplyiv version 3.0.0 that will be released in the next few weeks.

My collegue @pribossek and I are also designing halbach cylinders with magpylib.

This is your work right ?

[Magnetic_Dipole_Localization](https://www.researchgate.net/publication/337837184_A_Closed-Form_Formula_for_Magnetic_Dipole_Localization_by_Measurement_of_Its_Magnetic_Field_Vector_and_Magnetic_Gradient_Tensor
)

And what you suggested is to also provide the gradient Tensor in magpylib, correct?

**Comment by linhz0hz** [comment]
I can work on an example in a few weeks. Sorry that I am a little busy in near future.

I am not suggesting to provide a gradient tensor caculation yet. For permanent magnets, it might be easier to calculate the field around the region of interest then take numerical gradient as @laikh suggested, so I am not sure if providing analytical gradient calculation is the most useful.

The paper you quoted is not my work. My previous work was only an unpublished undergraduate project for an undergraduate level demo lab. But there are certainly many more serious research groups building permanent magnet Halbach arrays for serious portable NMR applications. I have read some of those publications when I was building it and used some of the ideas.

**Comment by OrtnerMichael** [comment]
If you mange to write a brief summary/example we would be very happy, but there is absolutely no stress about it. If you have time to comment on #272 we would apprechiate it a lot.
