### ISSUE TITLE
CI on mag3 - setting up test pipelines

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#258]
py_version v3.7, v3.8, v3.9, v3.10
- [ ] testing pipline
     - [x] windows with azure
     - [x] circle ci (linux?)

**Comment by lucasgcb** [comment]
Python 3.10 is not a stable release yet, so I've not added it to the pipeline.
I could still do it, but it would imply in always testing the latest 3.10 release (which is a bit wonky, as it changes often)

**Comment by OrtnerMichael** [comment]
no dont include it.
Anaconda Standard is now python 3.8

**Comment by OrtnerMichael** [comment]
@lucasgcb can we close this ?

**Comment by lucasgcb** [comment]
> @lucasgcb can we close this ?

Yep, it should have closed when PR #268 was merged.
