### ISSUE TITLE
CI with mag3 - setup.py

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#259]
- [x] find out for which (lower) versions the tests will work
 - numpy 1.20.1
 - scipy 1.6.0 (numpy-scipy dependency)
 - matplotlib 3.3.4
 - py_version v3.7, v3.8, v3.9, v3.10
- [x] magpylib3 -> magpylib naming
- [x] packaging (setup.py)

**Comment by OrtnerMichael** [comment]
working for
python 3.7.10,  3.8.8,  3.9.2
numpy 1.20.1
scipy 1.6.0
matplotlib 3.3.4

might work also with some lower version of numpy, scipy, matplotlib, but why bother supporting this ?

**Comment by lucasgcb** [comment]
> working for
> python 3.7.10, 3.8.8, 3.9.2
> numpy 1.20.1
> scipy 1.6.0
> matplotlib 3.3.4
> 
> @lucasgcb might work also with some lower version of numpy, scipy, matplotlib, any reason we should bother supporting this ?

Ideally, supporting earlier dependencies means it'll be easier to set up for users who may not be up to date. That's pretty much it. 

The risk of doing this would be older versions having features we use becoming deprecated, and having to update the library accordingly.

For now we can keep it with the dependencies we identified, I'll be working on the package script soonish.

**Comment by OrtnerMichael** [comment]
pip install . works now
