### ISSUE TITLE
CD with mag3

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#260]
use Circle CI to deploy tags in master automatically

new version is 3.0.0
no more beta versions !

- [x] automatically deploy to PyPI
- [x] automatically deploy to conda forge

**Comment by lucasgcb** [comment]
Technically already deploys to PyPi, just need to confirm the beta-to-official-release steps with the conda-forge peeps.

**Comment by lucasgcb** [comment]
I've cleared up on the conda-forge gitter for conda's first out-of-dev delivery and we're able to start deployment to PyPi.
We can now have a merge pertaining #296 towards the master brench whenever that's possible.
After that all we need to do is tag it, and I'll set the conda feedstock to auto deploy as well.

**Comment by OrtnerMichael** [comment]
i'll merge later this afternoon ... or feel free to merge any time :)

Lucas Gabriel Coliado Bandeira ***@***.***> schrieb am Sa.,
26. Juni 2021, 23:29:

**Comment by lucasgcb** [comment]
Updated everything, now our conda feedstock has automerge.
Adding this list for posterity:

- Version number in docs
- Version number in setup
- Version number in init dunder
