### ISSUE TITLE
documentation for mag3

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#261]
- [ ] DOCSTRINGS
    - [ ] interface function docstrings in scipy standard format
    - [ ] __init__ module docstrings
    - [ ] standardize and complete inside-package docstrings
- [ ] COMPLETE REWORK OF DOCUMENTATION (use scipy style)
    - [ ] magpylib with excel docu (suggestion from stefan herzog)
- [ ] CI/CD
    - [ ] setup read the docs for automatic doc upload
    - [ ] how to preserve the old documentations in read the docs

**Comment by lucasgcb** [comment]
The Sphinx we used (1.8.2) is at least 2 major versions behind the current one (3.5.1), once we get here maybe we should check to see if it's worth keeping it the old one or attempt to update it.

**Comment by OrtnerMichael** [comment]
issue was split up into small parts for PM reasons
