### ISSUE TITLE
Remove JavaScript analysis from LGTM

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#264]
LGTM is wastefully analyzing some JavaScript snippets we use for fluff in our documentation files.

This is not interesting since we do not touch these files, and must be disabled or it will trigger useless checks during pull requests, like in #263 

https://help.semmle.com/lgtm-enterprise/admin/help/disabling-analysis-language.html

**Comment by OrtnerMichael** [comment]
@lucasgcb 
I agree with removing the check.
But I did not manage to find the settings on the lgtm page.
You cannot do it because you are not an owner of the repository ?

**Comment by lucasgcb** [comment]
> @lucasgcb
> I agree with removing the check.
> But I did not manage to find the settings on the lgtm page.
> You cannot do it because you are not an owner of the repository ?

Yep, I do not have access to perform this configuration change.

**Comment by lucasgcb** [comment]
After double checking the page [I've now created an issue at their tracker](https://github.com/github/codeql/issues/5351) to see what's the solution for this. 

Apparently most of the process is automated and removing analysis is something exclusive to the enterprise edition, they have to disable this manually for us.

**Comment by lucasgcb** [comment]
[This is now fixed](https://github.com/magpylib/magpylib/pull/268), as they had to turn this off manually on their end.
