### ISSUE TITLE
Planned features longterm

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#265]
**Future features planned in this project that are not on their way yet.**

- force computation "getF"
- demagnetization computation using a method of moments
- numerical stability analyssi and guideline
- debug mode that performs extensive input format checks for inexperienced users
- custom source (=FEM source = Virtual field), give user the option to generate custom sources

**Comment by pribossek** [comment]
Implementationwise, demagnetization and force computation can both rely on the similair code for discretization of the magnetic system so it might be generally a good idea to combine these tasks. As a start, I can provide an implementation of discretization and force computation for cuboid magnets, however a suitable solution has to be found for other magnet shapes like cylinders and spheres where analytical solution for volume elements has to be found and implemented. Do we have solutions for cyldindrical and spherical volume elements?

**Comment by OrtnerMichael** [comment]
This collective issue is now partially completed, and the rest is split up into different issues
#349 
#347 
#348
