### ISSUE TITLE
Update Readme Flag/Banner (drop 3.6)

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#267]
Update [our flag](https://github.com/magpylib/magpylib/blob/master/docs/_static/images/magpylib_flag.png) to read "3.7+", as we won't support Python 3.6 any longer.

![](https://raw.githubusercontent.com/magpylib/magpylib/master/docs/_static/images/magpylib_flag.png)

**Comment by OrtnerMichael** [comment]
I have added the update task to #269 . We should consider to make smaller, more-icon-like logo.

**Comment by OrtnerMichael** [comment]
closed iwht new ongoing issue #284
