### ISSUE TITLE
To do for release 3.0.0

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#269]
- [ ] update banner
- [x] code: integrate sphere magnet class
- [ ] code: integrate current class Line
- [ ] code: integrate current class Circular (extend to/replace by Arc ?)
- [ ] code: integrate moment class
- [x] profile getBH_level2
- [x] complete CI #258
- [x] complete CI pylint #262 
- [ ] complete CD #260 
- [ ] complete docu #261 
- [ ] resolve naming convention #272 
---------
**final checks**
- [ ] final review of changelog (all changes)
- [ ] final docu review (all features)

--------
**maybe**
- [ ] integrate the tile class
- [ ] graphic defaults to Config

**Comment by OrtnerMichael** [comment]
omg this is a lot of work - but check out the new Sphere graphics :) 
![image](https://user-images.githubusercontent.com/47384012/111496788-df5cf500-8740-11eb-8510-3e8f548dec76.png)

**Comment by pribossek** [comment]
import numpy as np
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.tri as mtri


phi,theta=np.meshgrid(np.linspace(0,2*pi,100),np.linspace(-np.pi,np.pi,100))
r=1
x=r*np.cos(phi)*np.sin(theta)
y=r*np.sin(phi)*np.sin(theta)
z=r*np.cos(theta)
X=np.array([x.ravel(),y.ravel(),z.ravel()]).T
tris = mtri.Triangulation(phi.ravel(),theta.ravel())
fig = plt.figure()
ax  = fig.add_subplot(111, projection='3d')
ax.plot_trisurf(X[:,0], X[:,1], X[:,2], triangles=tris.triangles, cmap=plt.cm.bone)
plt.show()

![sphere](https://user-images.githubusercontent.com/22050435/111701323-f4b64a00-883a-11eb-94ad-850bc9ca0f48.PNG)

**Comment by OrtnerMichael** [comment]
as a result of discussion with @pribossek i have change the code back to very simple representation.
This eliminates 100 lines of code :) ... and the objects still look ok

![image](https://user-images.githubusercontent.com/47384012/111773091-f9681600-88ad-11eb-9dc0-8178a787d815.png)

**Comment by OrtnerMichael** [comment]
This was now replaced by a project
