### ISSUE TITLE
[Open Discussion] New source attribute naming convention for 3.0

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#272]
Currently in version 2.3.0b, source objects have their attribute names written out in full: [Example from the magnet box source](https://magpylib.readthedocs.io/en/latest/_autogen/magpylib.source.magnet/#magpylib.source.magnet.Box.magnetization).

```
.magnetization
Magnetization vector of box in units of [mT].

.dimension
Magnet dimension=[a,b,c] which correspond to the three side lengths of the box in units

.position
Position of the center of the magnet in units of [mm].

.angle
Angle of orientation of the magnet in units of [deg].

.axis
Axis of orientation of the magnet.
```

The API for the constructor currently makes use of keywords such as `mag`, `dim`, `pos`, `angle`, `axis` to set the value for these attributes.

In the upcoming 3.0.0 release, it has been suggested to shorten all the attribute names to match the API. We're also introducing a new relative position attribute regardless, which replaces both `axis` and `angle`. The current proposal for the attribute names is as follows:

```
.mag
Magnetization vector of box in units of [mT].

.dim
Magnet dimension=[a,b,c] which correspond to the three side lengths of the box in units

.pos
Position of the center of the magnet in units of [mm].

.rot
Present relative rotation of the magnet, returns a scipy rotation object.
```

 ---

It would be nice to have an open discussion with both developers and users to conclude whether this naming proposal is preferable over the new one, or to have the new proposals that may combine the qualities of both.

**Comment by lucasgcb** [comment]
From my perspective, the original attribute naming convention make magpylib simulation code the most legible; variable/attribute names being written out in full make it very explicit about what they represent at a glance, regardless of the level of familiarity one has with our library. For instance, `mag` is short for `magnetization`, but can be confused for the magnet word or the top level `magnet`package itself; the new `rot` attribute for the relative rotation object shares the same start of the `rotate` method, so it's very easy to confuse them both. One can still understand them given time and familiarity, but by removing information the room for mistakes is larger and the resulting code less comprehensible by nature.

Shortening names is often done to save time exclusively when writing code, but in this case code completion allows you to  enter the first character of the attribute and select it without a problem. Even if this wasn't the case, a known quote from the known Clean Code practice is that [more time is spent reading code than writing it](https://www.goodreads.com/quotes/835238-indeed-the-ratio-of-time-spent-reading-versus-writing-is), so a hit in code readability can lead to more impact to users who will certainly be reevaluating their simulations after they create them. 

Magpylib is often used wrapped in other projects, so users will most likely be working with other libraries and programming languages alongside it. By not forcing the information in simulation code to be as clear we can make it, users will be even less likely to understand what it reads, and have to defer directly to the documentation more often, which can be needlessly frustrating compared to the few seconds it would take to write out a full name originally.

That said, my proposal for 3.0.0 would be returning with the written out in full attributes, replacing `rot` with `relative_rotation`, and replacing the shortened keyword API with names written out in full, as well:

```
.magnetization
Magnetization vector of box in units of [mT].

.dimension
Magnet dimension=[a,b,c] which correspond to the three side lengths of the box in units

.position
Position of the center of the magnet in units of [mm].

.relative_rotation
Present relative rotation of the magnet, returns a scipy rotation object.
```

**Comment by pribossek** [comment]
I recently tested the magpylb 3.0 for the first tima and rewrote most of my previous code to be compliant with the new naming convention.  As a user, I prefer to use  names like mag, rot,dim as variables names. Luckily, python does not complain  and allows you to write something like Box(dim=dim), but this should be considered a bad practice. 
Anyhow, while attributes like pos, dim, mag are generally intuitive and therefore hard to be misinterpreted, the naming conventions for rotations are quite confusing. With "rot",  user might as well expect rotation matrix or rotation angles in any of possible Euler angle combinations. Instead, perhaps "rotation_object" or "rot_obj" would be appropriate names?

**Comment by OrtnerMichael** [comment]
I am personally in favor of the new short attribute names for the following reasons:

1. Moving to `mag`, `dim`, `pos` as attribute names, keeps the old API mostly intact. (I think we all agree that initialization the attribute `magnetization` with the kwarg `mag` is bad practice.
2. As @pribossek mentioned we have context i.e. we always have `magnet.mag` and `magnet.dim` so it is quite clear what they stand for. All users are aware that they have magnets and simulate magnetic fields.
3. We have everything explained nicely in the docstrings.
4. I personally find 

```
Box(mag=x, dim=y, pos=z, rot=u)
```
much more readable in big codes than 
``` 
Box(
   magnetization=x, 
   dimension=y,
   position=z,
   orientation=u)
```
I understand that the `rot` attribute name is probably a bad choice. Could be `orient`.

**Comment by 9Volts9er** [comment]
I agree with @OrtnerMichael. 

In my opinion the readability even profits from the short form, as you can keep a better overview over your complete code.
It may confuse mostly just programmers who are new to magpylib, but they will anyhow need to look into the documentation even when long attribute names are used. So in my opinion it's far more important to have a good documentation than full attribute names.

And for me the most important aspect is to keep the API more or less backward compatible. Otherwise it will be a lot of effort to change current scripts to version 3 (that's a very subjective argument as I have a lot of scripts that would need to be updated ;) ).

Nevertheless I understand that according to common coding conventions the full names would be the better choice. I just personally always prefer shorter writings.

**Comment by richard-ifx** [comment]
Adding one more voice as a regular user of the magpylib I would also vote for `mag`, `dim` and `pos` as attribute names. As @pribossek mentioned these names are already quite intuitive to understand in the code. If there is any ambiguity left I can find the information in the docstring, which I anyway have to read to know the details of the attribute (e.g. what is the meaning of the pos vector elements and the corresponding units). But in the end both variants have its advantages and are perfectly fine to integrate.

**Comment by OrtnerMichael** [comment]
**Translated from Benajmin K.**

I mostly don't care how the keywords and attributes are named.
I can understand both sides of the argument.
 - explicit expression is good
 - simpler code too

I do not belive that there will be misunderstandings due to strong context. Also there is the documentation. In any case it is impossible to give all information with the variable name. This would require something like
```
magnetization_vector_in_mT
```
Typically it is not enough to just read code.

**Comment by OrtnerMichael** [comment]
Translated from **User Stefan H.** to original post from @lucasgcb 

All arguments are understandable, but I would prefer the short namings.
This makes the code more readable.

I mostly copy code from old scripts when I do new computations and rarely go into the code for rewriting. If I have to rewrite then I anyways need so much brain-power that the abbreviations will be neither a problem nor helpful.

Less and shorter code is always preferable to me.

I really like the idea to replace ```rotation``` with ```orientation```. Rotation feels more like an operation that is applied, not so much like a "state".

**Comment by OrtnerMichael** [comment]
From **Perla M.** (magnetic simulation expert)

I also prefer short names. 
In my opinion it makes the code more readable and you can define your magnet properties mag, dim, pos, rot in just one line of code. 
Short names are also an advantage when you want to copy from old code. If long name will be introduced it will take a lot of time to change old codes according to new notation. 
Personally I do not see the need to use complete names.

**Comment by traavnik** [comment]
I like to make my names just verbose enough to not be ambiguous. Would vote for short form in this case. I also prefer `.orient `over `.rot` although it breaks the nice 3 letter pattern. Can't have everything.

API backward compatibility is not a valid concern to me for a least two reasons. They're already breaking it by merging `.angle` and `.axis` as mentioned in OP. I expect to see some more breaking changes throughout new code (didn't look). The other reason is convention. Bumping major version number (2.x.x -> 3.x.x) implies API change, which is probably a very conscious and well thought out decision by the authors. On the contrary, it would be very wrong if name change was delayed to any minor version update.

**Comment by OrtnerMichael** [comment]
**SUMMARY   -   WIP**  

plus side (long names)
- Zen of Python: "readability counts" code is read more often than it is written <<>> big unreadable code
- Zen of Python: "Explicit is better than implicit" <<>>  context is given
- e.g. mag is a good variable name <<>> mag=mag is not uncommon syntax


minus side (long names)
- missing nice and easy initialization Box(magnetization=(1,2,3))   <<>>   Box(mag), auto-completition
- code becomes big and unreadable  <<>> but sources are not initialized often
- backward compatibility, rewriting codes :( <<>> bumping version from 2 to 3
- variable name derivatives like pos_pix must also be renamed
- 3-letter pattern
- most users prefer short names

**Comment by OrtnerMichael** [comment]
** CONCLUSION **

We will go with explicit names for the following reasons:
1. good practice of programming
2. ppl who want short codes can still just use argument order `Box(mag,dim,pos)`

** we apologize to all ppl who have to rework their old v2 codes **

**Next step**

finding good names

**Comment by OrtnerMichael** [comment]
** ATTRIBUTE NAMES **

magnetization --- shorter alternative remanence
dimension
position
orientation
pixel_position

**Comment by OrtnerMichael** [comment]
completed with #330

- mag -> magnetization
- dim -> dimension or diameter
- pos -> position
- rot -> orientation (source attribute)
- src_typ -> source_type
- pos_pix -> pixel
- rot -> rotation (method argument)
- direc -> show_direction
- size_direc -> size_directions
