### ISSUE TITLE
Update banner to 3.0.0 - new Banner

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#284]
**Why a new logo**
1. We are moving to v3.0.0 - its a major update that will appeal to a large user base.
2. In the old logo there is a large bird and a small magnet. When the logo is iconized there is a small bird and nothing else. The focus should be on magnets, currents, sensors, magnetic fields.
3. We want to become NUMFOCUS affiliated. whichever logo we now choose will stay with us FOREVER !

**What should the new logo be like ?**

1. Represent the functionality better (magnet - currents - coils - sensors - fields)
2. Simpler and easy to recognize when iconized
3. If we manage to keep a small bird it would be nice (the magpie is our mascot in that sense).
4. The string "magpylib" should not be there anymore - but thre logo should be extensible to a banner with the font. 

**NUMFOCUS**
The new logo style should be somehow in-line with NUMFOCUS affiliated project logos
[numfocus affiliated projects](https://numfocus.org/sponsored-projects/affiliated-projects)

**Colorscheme**
There are currently 2 color schemes: normal and neon.

In the recent publication I introduced the Neon style
[new neon color scheme](https://www.sciencedirect.com/science/article/pii/S2352711020300170)

old color scheme
![image](https://user-images.githubusercontent.com/47384012/115106855-6e8b4180-9f67-11eb-8518-10a8fd313a01.png)

We could also pick a new color scheme.

Whatever we descide on - we will stick to it hereon. I will make the new documentation in this style. 

It should be mentioned that in the library we produce (very sucessfully) graphics using the HSV colorscheme.
![image](https://user-images.githubusercontent.com/47384012/115107175-8663c500-9f69-11eb-8fff-98a3f56d25bf.png)

Figures can look like this e.g.
![image](https://user-images.githubusercontent.com/47384012/115107239-ef4b3d00-9f69-11eb-96a2-2f389b7be2ee.png)

**idea for a logo**

maybe something like this (yes I am colorblind :) )

![image](https://user-images.githubusercontent.com/47384012/115102350-9cae5880-9f4a-11eb-8bb4-f91bc971f33e.png)

**Comment by lucasgcb** [comment]
Also these are a bit on the hard side for visualizing with GitHub's latest Night mode feature, which darkens the background:
![image](https://user-images.githubusercontent.com/7332704/120696747-46a65d80-c483-11eb-92d7-595fe98e1ca3.png)

Maybe we can add a white outline the text and vector lines? This way it won't show up in bright mode.

**Comment by OrtnerMichael** [comment]
Base logo: 
![image](https://user-images.githubusercontent.com/47384012/121035350-137b0b80-c7ae-11eb-9d86-9649711f784f.png)

**Comment by OrtnerMichael** [comment]
And we now do arbitrary variations about the base logo
![image](https://user-images.githubusercontent.com/47384012/121035430-2988cc00-c7ae-11eb-9aad-56c760230e77.png)

**Comment by lucasgcb** [comment]
Current banner looks like this on Nightmode, maybe it could use a white outline. I can do it if we agree on it:

![image](https://user-images.githubusercontent.com/7332704/121541021-4e16bb00-c9dd-11eb-9769-8bd2813b664e.png)

---

Also maybe the [downloads counter badge from conda cloud](https://anaconda.org/conda-forge/magpylib/badges) would be nice to have on our badges, rightmost? It updates automatically.

> ![image](https://anaconda.org/conda-forge/magpylib/badges/downloads.svg)

**Comment by OrtnerMichael** [comment]
i totally agree ... ill fix it

Lucas Gabriel Coliado Bandeira ***@***.***> schrieb am Do.,
10. Juni 2021, 16:20:

**Comment by OrtnerMichael** [comment]
This can be closed - we are happy with the new logo
