### ISSUE TITLE
[REQUEST] - sensor collections

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#297]
**user feedback**
Several users complained that the thought behind Sensors<->Pixel is different than the thought behind magnets <->Collections.

One should either include Sensors in Collections or make a new Collection class "SensorCollection" that provides the same functionality.

**problem**
Removing the pos_pix attribute makes the implementation of many sensors tedious

**advantage**
this would also be in-line with the feature request #279

**Comment by Alexboiboi** [comment]
lets move the discussion to #410
