### ISSUE TITLE
Visualization of magnetic field on principal planes

### ISSUE THREAD

**Issue by pribossek** [magpylib/magpylib#299]
I am often encountering the situation where given a certain magnetic collection, a magnetic field along the principal planes (XY,YZ,XZ) would need to be visualized.  While its pretty simple to code this, I feel this could become part of the magpylib alongside the current Display function.  Maybe one can even generalize this to every plane, where a plane can be  defined as combination of  point and a normal vector, and the desired discretization (number of pixels in the lateral dimensions). 
What do you others think of this?

**Comment by OrtnerMichael** [comment]
I think its a great idea and will be very simple to implement. How do you imagine the interface specifically ?

Like additional kwargs in display() ?
eg. `field_plane=None` by default and `field_plane=[normal_vector, anchor, discretization, color_function]` ?

**Comment by pribossek** [comment]
In the most general case, anchor and a normal vector do define the plane, but not the in-plane orientation of a grid on it. 
So in this case, an additional vector defining the horizontal axis of the grid is needed.  
Also for the discretization one has to provide the stepsize along the numbers of steps.
Maybe a dedicated function like below would be more suitable:
displayField(normal_vector, anchor_point, horizontal_axis=[1,0,0], discretization_step=(.1,.1), discretization_number=(100,100), color_function=jet, fieldlines=none, centered_on_anchor=True)

**Comment by OrtnerMichael** [comment]
Im hesitant to provide an automatic plotting function that ppl would use.
I have to assume that ppl know how to use matplotlib.
Otherwise they can copy-past codes from our examples.

I really like to idea to integrate a "quick preview" option (quiver based) in the display function - just to check if everything is fine.

How to generate a useful interface ? What information is needed ?

- discretization (int)
- normal vector (vec3)
- anchor (vec3)
- color_function (str)

- plotrange ? <- could be automatically the `sys_size`

@pribossek what is your `horizontal_axis` ?

**Comment by pribossek** [comment]
The implementation I had in mind was a simple 2D visualization of the magnetic field in the plane, displayed as an image. 
Quite often, the systems feature axis symmetries and in those cases, I plot simple 2D plots to check the field lines and validate the proper magnetization orientations etc. For this, a  2D field plot (component-wise or total amplitude plot), is - in my experience - the most useful one. If so, you have to define a plane with anchor and normal vector and then provide the orientation of the 2D display to define the in-plane orientation of the 2d grid in the plane  This orientation is defined by a vector called "horizontal_axis". 

I think what you propose is a full 3D visualization of magnetic field, which is the most general visualization case. This can be useful too, but is not what I meant in the first place.

**Comment by OrtnerMichael** [comment]
I understand. 

For the field lines case I propose that you write your own wrapper function. I think most users will have troubles really understanding what this projection actually means - it will look good, but confuse as the fields are in 99% of the cases not in-plane.

However - amplitude plot can be easily done on arbitrary planes. That would be a very good addition - field an amplitude - I have to see how this can be combined with display.

**Comment by Alexboiboi** [comment]
> 99% of the cases not in-plane.

Just as a side note, it's pretty trivial detect out of plane field beforehand and issue a user warning when plotting field lines if it is above a certain epsilon.

**Comment by OrtnerMichael** [comment]
its not complicated to do this by hand - also we have a good docu example ...
