### ISSUE TITLE
matplotlib v 3.4 or later

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#300]
@lucasgcb
I justed noticed that pytesting fails when matplotlib is 3.2.
magpylib3 should work with matplotlib 3.4+ !
Please add this to the wheel/requirements/whatever it is that installs these packages :)

**Comment by lucasgcb** [comment]
In our setup.py for v3 it states [we only support 3.3 and over](https://github.com/magpylib/magpylib/blob/bff24403fc414630c17ef908a0ffadd3348062f6/setup.py#L67), was the package installed in the appropriate environment when the tests were run?

**Comment by OrtnerMichael** [comment]
strange, matplotlib 3.2 was installed when I conda-installed magpylib2. I tried to reproduce this but I cant.

pytests are working for both matplotlib 3.3.4 and 3.4.1.

I guess we can close this issue then
