### ISSUE TITLE
[TASK] Add our LICENSE notice to every v3 file 

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#302]
This is the notice we used before. It needs to be at the top of pretty much every single source code file we ship out.

```
# -------------------------------------------------------------------------------
# magpylib -- A Python 3 toolbox for working with magnetic fields.
# Copyright (C) Silicon Austria Labs, https://silicon-austria-labs.com/,
#               Michael Ortner <magpylib@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
# The acceptance of the conditions of the GNU Affero General Public License are
# compulsory for the usage of the software.
#
# For contact information, reach out over at <magpylib@gmail.com> or our issues
# page at https://www.github.com/magpylib/magpylib/issues.
# -------------------------------------------------------------------------------
"""
```

**Comment by laikh** [comment]
i know this is the official statement of the fsf, however it is not state
of the art anymore. i have discussed this issue with the professionals from
the Python Academy. From a legal point of view, it is enough to just
deliver the licence only once in a separate ? *.lic ? file for the whole
package. This is also the reason why i took out the headers from the code.

Lucas Gabriel Coliado Bandeira ***@***.***> schrieb am Di.,
4. Mai 2021, 14:25:

**Comment by lucasgcb** [comment]
> i know this is the official statement of the fsf, however it is not state of the art anymore. i have discussed this issue with the professionals from the Python Academy. From a legal point of view, it is enough to just deliver the licence only once in a separate ? *.lic ? file for the whole package. This is also the reason why i took out the headers from the code.

If we can trust their legal advice then this issue may be closed, however I see less confusion in keeping the source code bound to the license this way. The license notice is also the only one signed and provided by SAL, so I guess we should at least update the LICENSE file to reflect this if we decide not to append the snippet.

**Comment by OrtnerMichael** [comment]
So i should have mentioned that I tried to follow scipy code layout (docstrings, comments, ....). They just have a LICENSE.text file and no headers inside their library.

**Comment by OrtnerMichael** [comment]
things are now with the SAL legal department

**Comment by OrtnerMichael** [comment]
![image](https://user-images.githubusercontent.com/47384012/121376691-03943080-c942-11eb-9b1e-9805a0b80823.png)

sw33t
