### ISSUE TITLE
[TASK] Add .github settings in new version

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#304]
The latest development branch does not have [.github](https://github.com/magpylib/magpylib/tree/master/.github), which offers some community configuration for our repository.

**Comment by OrtnerMichael** [comment]
@lucasgcb is this now settled with #305 ?

**Comment by lucasgcb** [comment]
> @lucasgcb is this now settled with #305 ?

Yep, the relevant Pull Request has been approved and merged so this task is completed as result.
