### ISSUE TITLE
[Issue] 2.3.0-beta tag with 2.0.1-beta docs

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#306]
We just noticed the [2.3.0-beta was shipped with 2.0.1-beta docs](https://magpylib.readthedocs.io/en/2.3.0-beta/). We updated the docs after shipping, since.

Let's evaluate if we want to make a new tag with the latest version, then archive that new tag on readthedocs, instead. If necessary so, the tag mustn't trigger deployment by having a unique but descriptive name.

**Comment by OrtnerMichael** [comment]
I think I got it ... best to make a 2.3.1 tag with everythin old and keep it as "final v2 version" in the archive

**Comment by OrtnerMichael** [comment]
we forget about this

if you are working with version 2 its your own fault
