### ISSUE TITLE
[TASK]  Rework Numpy Docstring Convention

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#327]
- [x] Rework Docstrings with [Numpy convention](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html), as per Napoleon for Sphinx
- [x] Remove Method descriptions from Class Docstrings: 
 - [Example how it used to be for v2.3.0 without methods in class docstrings](https://magpylib.readthedocs.io/en/2.3.0-beta/_modules/magpylib/_lib/classes/collection/#Collection)
 - [Rendered Example](https://magpylib.readthedocs.io/en/2.3.0-beta/_autogen/magpylib/)

- [ ] Review Docstring changes

**Comment by OrtnerMichael** [comment]
@lucasgcb this should be fine with #331 

please review and close
