### ISSUE TITLE
[REQUEST] Update Sphinx from V1.8 to V4 

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#328]
**Is your feature request related to some problem? If yes, please describe.**
Older version of Sphinx (1.8) is only supported on Python 3.7 and below; this will become increasingly frustrating.

**Describe the feature you'd like**
Update Sphinx to V4, along with the documentation configuration

**Additional context**
Watch out for auto doc breaking. It's the only reason we haven't tampered with it yet.
After it's working, we will have to manually modify Readthedocs build process.

**Comment by OrtnerMichael** [comment]
works with #396
