### ISSUE TITLE
[minor Bug] - keep webpage image ratio

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#337]
Can we add html code so that the github webpage images automatically adjust to page width ?
Currently i get this
![image](https://user-images.githubusercontent.com/47384012/121750942-9634fb00-cb0d-11eb-921b-3b273fb53bf5.png)

and

![image](https://user-images.githubusercontent.com/47384012/121750979-a4831700-cb0d-11eb-8c14-f5e177b33f62.png)

when viewing on my phone e.g.

**Comment by lucasgcb** [comment]
This should be fixed with #338 
Preview:
![image](https://user-images.githubusercontent.com/7332704/121754772-d5525480-caeb-11eb-8616-3920d0766892.png)

**Comment by OrtnerMichael** [comment]
great ty !
