### ISSUE TITLE
[possible problem] with numpy 1.20.3

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#339]
magpylib did not work with the new numpy 1.20.3

figure out whats wrong

**Comment by lucasgcb** [comment]
What tests break with this version?

**Comment by OrtnerMichael** [comment]
There was a problem with the installation. When numpy 1.20.3 was installed with conda a pip-install of magpylib led to problems.

However, its does not seem to be reproducible.

Also there is now numpy 1.21.0
