### ISSUE TITLE
Force/Torque computation

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#348]
A magnet.getF(magnet) seems to be a practical extension. However - it relies on a meshing algorithm. The meshing from **demagnetization** can/should be used here.

This feature is planned for after full interaction demagnetization.

**Comment by pribossek** [comment]
I have a working vetorized code for getF alongside the arbitrary discretization, however for now,  only cuboid magnets are supported.  Unless your code is more evolved as mine, I am happy to file a pull request. Minor adaption for recent v2-v3 changes might be required though.

**Comment by OrtnerMichael** [comment]
We should defenately get started on ``getF`` ... ``demag`` is also work in progress already. First we need
1. API suggestion, I would e.g. propose ``magpy.getF(sources1, sources2)`` and ``source.getF(sources)`` ... ``getFv`` ?
2. package internal structure - for this we need to understand what functions / methods are needed for the computation, can we simply inherit from am base class? are we going to have a getFv ? What is the current structure of your code ?

Probably there must be a grid function for all geometries where finesse can be adjusted. This could be shared with ``demag``.

**Comment by OrtnerMichael** [comment]
This functionality requires discretization. As this is generally non-trivial, this functionality could be integrated into the tool package ? #413

**Comment by OrtnerMichael** [comment]
see #787
