### ISSUE TITLE
[REQUEST] Custom/Virtual source

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#349]
The user should have the option to define a field that is generated by a source, and use that source in the Magpylib interface.

**Practical application**
The source could be a pre-computed and interpolated FEM-field, a measurement, or simply an arbitrary function.

**Interface**
```magpylib.misc.Custom(position, orientation, field=0)``` where field is a given function.

**Comment by Alexboiboi** [comment]
Also discussed in #409 and already implemented in #411
