### ISSUE TITLE
Box -> Cuboid

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#350]
I want to rename **Box** with **Cuboid**

please vote for or against
@lucasgcb 
@pribossek
@Alexboiboi

**Comment by OrtnerMichael** [comment]
input is welcome from anybody else as well
@jcafhe 
@traavnik
@closega
@9Volts9er
@richard-ifx
@JohnnyGG273

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael,

Since you have a major version change I don't see any issue to rename the `Box` class. Aslo it is a more mathematical term as are `Cylinder` and `Sphere`, so I am in favor for it

**Comment by richard-ifx** [comment]
For me both options are perfectly fine :)

**Comment by lucasgcb** [comment]
I am absolutely positive for this change.
I think Box as a name was originally chosen over Cuboid for brevity/simplicity.

**Comment by pribossek** [comment]
Cuboid is mathematically accurate expression while box is not, hence my vote goes for cuboid.

**Comment by OrtnerMichael** [comment]
This will go as ``Cuboid`` to v4 then #360
