### ISSUE TITLE
Matplotlib -> Mayavi or plotly

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#353]
The mayavi mlab package offers proper display of intersections

http://docs.enthought.com/mayavi/mayavi/index.html

This is just a nightmare in Matplotlib

![image](https://user-images.githubusercontent.com/47384012/124747698-7cc37b00-df22-11eb-9e49-ad961a4c3e79.png)

In their help they refer to using Mayavi instead.

So if someone is bored and wants to rewrite the display function :)

**Comment by OrtnerMichael** [comment]
From discussion with @Alexboiboi 

Matplotlib should remain as the standard backend (most common library that everyone has)

Mayavi or plotli backends can/should be activated via kwarg in ``display()`` for ppl who want to have it nice.

**Comment by lucasgcb** [comment]
> From discussion with @Alexboiboi
> 
> Matplotlib should remain as the standard backend (most common library that everyone has)
> 
> Mayavi or plotli backends can/should be activated via kwarg in `display()` for ppl who want to have it nice.

This would involve having Mayavi/Plotli as dependencies in the project alongside matplotlib, even if users don't use them.

A (tricky) alternative is creating magpylib display packages people can download then import, relying on a specific version of magpylib. This would take some thought, though.
