### ISSUE TITLE
[BUG] - Update Magpylib using conda does not work

### ISSUE THREAD

**Issue by Elroubya** [magpylib/magpylib#354]
**Describe the bug**
I have magpylib version 2.3.0b installed using conda then after the release of the new version Magpylib 3.0.0
then i tried to update magpylib using conda but it did not work.

**To Reproduce**
use the normal conda command : conda update magpylib 
this will update the magpylib but does not apply in spyder even if the kernel is restarted.
It is remarkable that the magpylib update works very well by the work around (using the pip)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - IDE [Spyder, Anaconda]

**Comment by lucasgcb** [comment]
Hi, Erlouby. Thanks for stopping by.

As per conda docs, [`conda update` doesn't update](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/installing-with-conda.html#conda-update-versus-conda-install) major versions by default. The latest Magpylib version is a major version number change (v2 to v3); and major version changes imply that previous code and scripts won't be compatible. This is done to keep libraries in your environment patched, but avoids breaking changes natural from major number bumps. It's pretty nifty.

So, to download magpylib v3 from magpylib v2 you'd have to do `conda install magpylib` instead. If you run into more issues, please let us know.

Thank you!

**Comment by Elroubya** [comment]
Hi Lucas,
Thank you very much for your support, i tried also this technique : conda install magpylib and it made the update but did not reflect on spyder, then i tried another way to uninstall magpylib then reinstall it but it did not also reflect on spyder.
The only work around until now is using pip.
If you want me to try another techniques i would be glad to do so.

Thank you!

**Comment by OrtnerMichael** [comment]
im closing this now, please reopen if there is still something to do
