### ISSUE TITLE
[REQUEST] - Magpylib compounds sub-package

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#355]
requests
-------------

Many users are asking for APIs of simple implementations.

Some users offer to provide us with useful implementations of magnet compounds. Examples are **Halbach structures**, or various **MPO systems** (like Joysticks etc.).

idea
---------

We could add a top level subpackage "systems" where we collect complete good implementations of such systems from users.

**Comment by Alexboiboi** [comment]
This is partially adressed by #458

@OrtnerMichael should we close this?

**Comment by OrtnerMichael** [comment]
yes
