### ISSUE TITLE
Improve CylinderSegment

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#357]
List of things to do to complete this
- [x] figure a good interface out #362 
- [x] Complete implementation of diametral solution @OrtnerMichael @lukasrauber
- [ ] cel -> PI
- [ ] el3 code coverage to 100%
- [ ] profile ``Tile`` code` @fslanovc @OrtnerMichael
- [ ] discuss hollow cylinder solution @lukasrauber @OrtnerMichael 
- [ ] discussion on numerical instability of ``Tile`` solution @fslanovc
- [ ] improving the tile code by stacking similar ``el3`` and ``cel`` evaluations @fslanovc
- [ ] C-extension for ``cel`` and ``el3`` @JohnnyGG273

**Comment by lukasrauber** [comment]
just leaving a message here to be contacable regarding closed form solutions for the magnetic field of diametrally magnetized cylinders (as discussed with @OrtnerMichael )

**Comment by OrtnerMichael** [comment]
Hi @lukasrauber ,
ty for participating and ty for providing a diametral solid cylinder solution in a closed form. I'm now trying to work out the field components.

**Comment by OrtnerMichael** [comment]
**Idea:**
We compute ``cel`` but most of the time we use only ``PI``. There are designated algorithms for ``PI`` that are very fast. This could increase performance by a lot.

https://www.sciencedirect.com/science/article/pii/S037704271300201X

**Comment by OrtnerMichael** [comment]
all above tasks are by now not necessary or in other issues.

The CylinderSegement profiling and code improvements will be do with C-extensions in the future which makes explicit vectorization unecessary.
