### ISSUE TITLE
VOTE - v4 new names for getBv and getHv

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#361]
Unfortunately v3 was a bit premature.

With ``Box`` -> ``Cuboid`` (its a must) the API is broken and we have to move to v4.0.0 with the next patch. After a thorough review of all features (see #360 ) the only remaining namechange must be of ``getBv`` and ``getHv``.

These top-level functions avoid the object oriented interface and give direct access to the analytical formulas based on complex dictionary inputs. Its the fastest way to compute the field in Magpylib if you know how to vectorize code properly (but even then not much faster than the object oriented interface).

Please propose names @lucasgcb  @pribossek  @Alexboiboi 

``getB_direct`` ?
``getB_a_little_faster`` ?

**Comment by lucasgcb** [comment]
The `v` suffix stands for `vectorized`, right?
The `getB_direct` option seems good since its purpose is to avoid the object oriented interface.

I had thought of suggesting `getB_dictionary`, but looking at [the documentation](https://magpylib.readthedocs.io/en/latest/_autogen/magpylib/#magpylib.getBv) I'm not seeing any [python dictionary ](https://docs.python.org/3.7/tutorial/datastructures.html#dictionaries) inputs for these functions. Is there a reason for this term?

**Comment by OrtnerMichael** [comment]
Any input is ofc welcome - and ty for participating to make the magpylib interface maximally intuative
@richard-ifx
@9Volts9er
@traavnik
@lukasrauber
@JohnnyGG273

**Comment by OrtnerMichael** [comment]
@lucasgcb Well in Magpylib2 we added vectorized code for the first time in the ``getB_Box_vector()`` functions. The name ``getBv()`` derivates from that as the functionality (dictionary input) is quite similar. However, now everything is vectorized automatically all the time and ``getBv()`` is just there for users who want to squeeze out all possible performance by avoiding the object oriented interface overhead. The performance gain is not massive anymore (factor 1.1-2), and you only get that if you properly generate the input using ``np.tile`` and similar commands instead of ``for`` loops.

**Comment by lucasgcb** [comment]
> @lucasgcb Well in Magpylib2 we added vectorized code for the first time in the `getB_Box_vector()` functions. The name `getBv()` derivates from that as the functionality (dictionary input) is quite similar. However, now everything is vectorized automatically all the time and `getBv()` is just there for users who want to squeeze out all possible performance by avoiding the object oriented interface overhead. The performance gain is not massive anymore (factor 1.1-2), and you only get that if you properly generate the input using `np.tile` and similar commands instead of `for` loops.

In this case I find that `getB_direct` is appropriate, as the name refers to what it is meant to do: directly execute these formulas for calculating the B-field while bypassing overhead. Maybe `getB_bypass_overhead` would be the more precise naming? `getB_bypass`?

This way, if we ever change _how_ this code overhead bypass is implemented, then the method API won't be affected, and we won't need to worry about any inconsistency of the naming for users.

**Comment by pribossek** [comment]
Cant you keep the getB for standard computation (vectorized from v3 onwards)  and getBv for people who want to do vectorization on their own?

**Comment by OrtnerMichael** [comment]
@pribossek We want to keep both for sure - its just a naming issue. Its in no way clear for a user what ``getBv`` does from the name itself. Just trying to figure out if we want to change that name - and if so, we should do it now.

**Comment by OrtnerMichael** [comment]
completed with #375
