### ISSUE TITLE
VOTE - v4 Cylinder interface

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#362]
We now have the solid Cylinder and the Cylinder Tile combined in a single class with ``dimension=(d,h,di,phi1,phi2)`` where ``di, phi1`` and ``phi2`` are treated as optional.

**Option 0: the way it is right now**
I'm a bit unhappy with this - the argument mixture is just horrible.

**Option 1: two classes**
``Cylinder(dimension=(d,h))``
``CylinderTile(dimension=(d1,d2,phi1,phi2,h))``

**Option 2: kwargs**
``Cylinder(dimension=(d,h), di=0, phi1=0, phi2=360)``

@lucasgcb 
@pribossek 
@Alexboiboi 
any other ideas ?

**Comment by lucasgcb** [comment]
Visually it may make the most sense to have these two separated in order to not make the scripts confusing to read. If they're the same method call but return different things, you'd always have to check the arguments instead of just the method name to figure out what it returns, and that's really rough. 

Finding patterns to replace if need be would also get complicated because of this, so them being separate makes the most sense to me.

**Comment by OrtnerMichael** [comment]
Any input is ofc welcome - and ty for participating to make the magpylib interface maximally intuative
@richard-ifx
@9Volts9er
@traavnik
@lukasrauber
@JohnnyGG273

**Comment by pribossek** [comment]
To me it seems unclear what "cylinder tile" stands for. I guess what you mean by tile is a cylindrical segment in a shape of cylindrical volume element (dV in polar coordinates). However,  in Python numpy.tile does a replication of an array, so people might interpret this in a similair way and expect the function returns array of cylinders. 
To avoid confusion I suggest to change the name to CylinderSegment, if you want to go with Option 1.
I would however prefer the Option 2, it seems the easiest to remember and use from the user perspective.

**Comment by OrtnerMichael** [comment]
@pribossek I like ``CylinderSegment`` a lot. In scientific literature this is mostly referred to as Cylinder Tile or as Ring Segment. Florian will publish it a s Cylinder Tile.

Concerning option 2 - I really like that a lot too - @lukasrauber suggested it for the first time - but it would break the whole idea of the ``dimension`` input - and with our explicit naming convention we would have to call the kwargs ``angle1``, ``angle2`` an``inner_diameter`` ...

**Comment by OrtnerMichael** [comment]
closing this now

we have **CylinderSegment** as class name and `_object_type` and **magnet_cylinder_tile_H_Slanovc2021()** in `dict`

This was already added in #373 to the development branch
