### ISSUE TITLE
[QUESTION] - How to model the field distribution of current coli as a Cylinder shape. Currently in magpylib, there are only circular and line model with current.

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#363]
**Problem description**

**Comment by OrtnerMichael** [comment]
hi @caimingxue 

Thanx for contacting us. This is probably what you want. There will be docu examples up on read the docs in the near future.

https://magpylib.readthedocs.io/en/latest/

```
import numpy as np
import matplotlib.pyplot as plt
import magpylib as magpy

# create figure using Matplotlib
fig = plt.figure(figsize=(8,4))
ax1 = fig.add_subplot(121, projection='3d')  # 3D-axis
ax2 = fig.add_subplot(122,)                  # 2D-axis

# create a Magpylib collection of Circular Sources that form a coil
coil = magpy.Collection()
for z in np.linspace(-2,2,20):
    winding = magpy.current.Circular(
        current = 1,
        diameter = 5,
        position = (0,0,z))
    coil += winding

# display the coil on ax1
coil.display(axis=ax1)

# create a grid
ts = np.linspace(-6,6,30)
grid = np.array([[(x,0,z) for x in ts] for z in ts])

# compute field on grid
B = magpy.getB(coil, grid)
amp = np.linalg.norm(B, axis=2)

# display field in figure with matplotlib
ax2.streamplot(grid[:,:,0], grid[:,:,2], B[:,:,0], B[:,:,2],
    density=2, color=np.log(amp), linewidth=1, cmap='autumn')

plt.tight_layout()
plt.show()
```

![image](https://user-images.githubusercontent.com/47384012/126059164-fc81a485-f150-4393-98ab-92731bb2d6ae.png)

**Comment by caimingxue** [comment]
Hi,  @OrtnerMichael@OrtnerMichael, thanks for your reply. It is a good work. Meanwhile, for the coil, we often add a soft iron or other materials to improve the magnetic field. So, I want to ask how to add this cylinder core in the coil. Moreover, If we generate a desired magnetic field, we can put a magnetic object in it, the object will generate motion under this field, how to simulate this. Finally, how to show the field just like the simulation result in COMSOL with different color gradient.

****

**Comment by caimingxue** [comment]
Just like this <img width="515" alt="coil" src="https://user-images.githubusercontent.com/45029643/126100562-1c4e3359-a612-4105-a152-4f6a84ee2c24.png">
@OrtnerMichael

**Comment by caimingxue** [comment]
<img width="515" alt="coil" src="https://user-images.githubusercontent.com/45029643/126101795-ed0d37d5-d067-4bae-b728-b16cd4cd2dd9.png">

**Comment by OrtnerMichael** [comment]
Hi @caimingxue 
1. soft-magnetics do not work with Magpylib yet. However you can easily model it yourself by adding a set of small ``CylinderSection`` sources, and compute the interaction according to B=H+M and some material law M=chi H. This is oftern refferred to as "Magnetostatic Method of Moments".
2. I dont know what you mean by motion. You can compute the force that acts on an object using simple force models F=(m⋅∇)B
3. To plot using color gradients I suggest you read the Matplotlib tutorial

**Comment by caimingxue** [comment]
Hi @OrtnerMichael , thanks for your patient reply. I have resolved the question 3. For the question 2, what i mean is a magnetic agent in the any position of generated magnetic field, what is the force and torque imposed on it, so it will be driven by the field and have a motion. Just like the following picture in your document. "The field computation is coupled to a geometry interface (position, orientation, paths) which makes it convenient to determine relative motion between sources and observers."
<img width="893" alt="coil" src="https://user-images.githubusercontent.com/45029643/126129288-f0c5f1a7-0a09-430e-877b-984a54a85848.png">

**Comment by OrtnerMichael** [comment]
hi @caimingxue ,

Well thank you for pointing out this misunderstanding - motion was not meant as in "equations of motion" but simply as relative positioning. You can use Magpylib to solve the equations of motion, but its not implemented as a tool. In principle all you have to do is to compute the force via F(r)=(mag(r)⋅∇)B(r) and then solve the equation of motion mass*r'' = - F(r) where r stands for the position and mag(r) stands for the magnetization of your agent. This magnetization you could simply approximate on a grid inside your agent.

Its a funny example, and easy to implement - I will think of making it an example code. It you want, you can also implement it, I would review and give you feedback , and eventually post it on the webpage. I've made this an issue #365

**Comment by OrtnerMichael** [comment]
I'm closing this issue. Please reopen if there are more questions
