### ISSUE TITLE
[REQUEST] How to generate a 3-D rotating magnetic field?

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#369]
**Is your feature request related to some problem? If yes, please describe.**

**Describe the feature you'd like**

**Describe alternatives or solutions you've considered**

**Additional context**

**Comment by OrtnerMichael** [comment]
hi @caimingxue 

Please write your issues with more detail.

I can only guess that you refer to a rotating magnet ?
Have a look at the ``rotate_from_angax()`` method.

The following code will rotate a magnet:
```
import magpylib as magpy

# create magnet
src = magpy.magnet.Cylinder(magnetization=(1000,0,0), dimension=(2,2))

# rotate magnet by 90 deg
src.rotate_from_angax(angle=45, axis='z', anchor=0)

# display orientation of magnet
print(src.orientation.as_euler('xyz', degrees=True))

# create a rotation path
src.rotate_from_angax(angle=[30,60,90,120,150,180], axis='z', anchor=0)

# display orientation of magnet
print(src.orientation.as_euler('xyz', degrees=True))

# compute "rotating" B-field for all magnet rotations
B = src.getB((0,0,3))
print(B)
```

check out the docstrings of the method - there is a lot of functionality that will make creating complex paths rather easy.

You can also find good example codes and explanations here

https://magpylib.readthedocs.io/en/development/

sincerely,
michael

**Comment by OrtnerMichael** [comment]
Im closing this. Please reopen if there are more questions.
