### ISSUE TITLE
Choose input/output units - make computations dimensionless

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#378]
# Feature

**add `defaults` options**
     - `defaults.units.magnetization='mT'`
     - `defaults.units.B = 'mT'`
     - `defaults.units.H = 'kA/m'`
     - `defaults.units.current='A'`
     - `defaults.units.length='mm'`

**make computations dimensionless**
why is this not the case yet ?

**Comment by OrtnerMichael** [comment]
- Must keep B and H !
 - maybe add a default option
     - `defaults.units.magnetization='mT'`
     - `defaults.units.B = 'mT'`
     - `defaults.units.H = 'kA/m'`
     - `defaults.units.current='A'`
     - `defaults.units.length='mm'`

**Comment by Alexboiboi** [comment]
some useful links

https://pint.readthedocs.io/en/stable/
