### ISSUE TITLE
[REQUEST] - give Collection the __len__ property

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#383]
generally it would be nice for Collections to behave like a Python list- the len() property is missing.

possible ways to solve this:
1. maybe one could inherit the list and add Collection methods.
2. or just add the \_\_len\_\_() dunder

**Comment by Alexboiboi** [comment]
It is  generally not a good idea to inherit from builtins such as `list`.

See here why: https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/

I took the liberty to implement the dunder here: https://github.com/magpylib/magpylib/commit/6fc6bc4490fcced4f783be94f789d459c86051b6
