### ISSUE TITLE
[QUESTION] - How to rotate a magnetic object with absolute angle, However, the param "increment" in rotate does not work well

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#384]
**Problem description**
from scipy.spatial.transform import Rotation as R
import magpylib as magpy

dipole = magpy.misc.Dipole((1,2,3))
print(dipole.orientation.as_euler('xyz', degrees=True))

dipole.rotate(R.from_euler('x', [45], degrees=True))

dipole.rotate(R.from_euler('x', [45], degrees=True), increment=Fasle)

print(dipole.orientation.as_euler('xyz', degrees=True))

**Comment by OrtnerMichael** [comment]
hi,

glad to see you are still working your way through the magpylib API :)

to **set** an angle you do not use rotate but simply do this:

```
from scipy.spatial.transform import Rotation as R
import magpylib as magpy

dipole = magpy.misc.Dipole((1,2,3))

dipole.orientation = R.from_euler(...)
```

Rotate is only needed when "adding" to the existing orientation(angle).

The ```increment``` kwarg is only used when you generate a path (multiple angles) - in the sense that these angles will be interpreted as absolute or as increments of each other.

**Comment by caimingxue** [comment]
Thanks for your reply. Recently, I focus on coils, which is a collection of circular objects. Your methods can achieve this goal, i.e., if the coils have many circulars, every circular needs to be set orientation, just like the following codes, but how to change the anchor of this method, default is the world frame. We usually hope to rotate the coil by its center. In my methods, before rotation using rotation matrix, the coils will be rotated to make its rotation matrix be identity matrix, then rotate the coil to desired rotation matrix. The rotate function can modify the anchor.  So, which one more time-consuming.

circulars = [magpy.current.Circular(current=1, diameter=2, position=[0, 0, origin_z])
            for origin_z in np.arange(10 - 10 / 2, 10 + 10 / 2, 0.5)]
coil_a = magpy.Collection(circulars)

for src in coil_a:
    src.orientation = R.from_rotvec([0, 0, np.pi/2])
    print(src.orientation.as_euler('xyz', degrees=True))
for src in coil_a:
    src.orientation = R.from_rotvec([0, 0, np.pi / 3])
    print(src.orientation.as_euler('xyz', degrees=True))

**Comment by OrtnerMichael** [comment]
hi,
not sure if I understand the problem ... the provided methods allow you to apply any possible rotation about arbitrary axes and arbitrary anchor points. The interface is missing an anchor-rotation TO a designated orientation - but as this is easily resolved by using an inverse rotation before applying your target rotation (see code below) it's hardly worth it to introduce another kwarg.

I think this code might resolve your issues.

```
import numpy as np
from scipy.spatial.transform import Rotation as R
import magpylib as magpy

# create a coil with designated center
coil_center = np.array((1,2,3))
zs = (-.2, -.1, 0, .1, .2)
loop_centers = coil_center + np.array([(0,0,z) for z in zs])
circs = [magpy.current.Circular(1, 1, lc) for lc in loop_centers]
coil = magpy.Collection(circs)

# set coil target orientation
R1 = R.from_euler('xyz', (.1,.2,.3))

# rotate the coil
coil.rotate(R1, anchor=coil_center)
print(coil[0].orientation.as_euler('xyz'))

# set another coil target orientation
R2 = R.from_euler('xyz', (.2,.3,.4))

# rotate coil to new target orientation
coil.rotate(R2*R1.inv(), anchor=coil_center)
print(coil[0].orientation.as_euler('xyz'))
```

of which the output should be
```
[0.1  0.2  0.3]
[0.2  0.3  0.4]
```

**Comment by caimingxue** [comment]
Thanks, it also works.
