### ISSUE TITLE
more practical implementation of CylinderSegment

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#386]
Use radii for CylinderSegment arguments - its much more practical for actually working with them.

This breaks the "size/diameter" convention but the segment is anyways never "full".

**Comment by OrtnerMichael** [comment]
only a single angle is necessary to define the CylinderSegment !

**Comment by OrtnerMichael** [comment]
@Alexboiboi
- The variable redefinition and docstrings are complete.
- Only the graphic output needs to be adjusted.
- The doku example should also be changed - but as you are reworking the doku I leave that for now

**Comment by Alexboiboi** [comment]
closed by #408
