### ISSUE TITLE
getB squeeze - sumup bug

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#425]
The following code generates two different outputs

```
import magpylib as magpy

s = magpy.Sensor(pixel=(1,2,3))
ss = magpy.magnet.Sphere((1,2,3), 1)

B = magpy.getB(ss, s, squeeze=False)
print(B.shape)
B = magpy.getB(ss, s, squeeze=False, sumup=True)
print(B.shape)
```

output:
(1, 1, 1, 3)
(1, 1, 3)

sumup reduces the B-array b the source dimension

add `keepdims=True` in `sum(B)` in level2 AND level2_dict ?

**Comment by Alexboiboi** [comment]
fixed by #426
