### ISSUE TITLE
Cannot hide path lines when path='animate' and a few bugs on the way

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#432]
I generate an object with a path
```
import magpylib as magpy

s1 = magpy.magnet.Cuboid((0,0,1), (1,1,1))
s1.move([[1,0,0]]*10, increment=True)
```
I want to display, but I don't want to see the path line. This I would find logic, but it does not work
```
s1.display(backend='plotly', path='animate', style_path_show=False)
```

So I use matplotlib logic setting linestyle='' - this is also not accepted
```
s1.display(backend='plotly', path='animate', style_path_line_style='')
```

Then I notice that dotted style is set with `'.'` and not `':'` is is done in matplotlib

Anyways - then I try setting linewidth=0
```
s1.display(backend='plotly', path='animate', style_path_line_width=0)
```
But this still leaves a path behind somehow
![image](https://user-images.githubusercontent.com/47384012/146737222-38f00302-39c0-4445-954b-47435554d184.png)

If I set linewidth=0.00001
```
s1.display(backend='plotly', path='animate', style_path_line_width=0.0001)
```
Then the path finally disappears - but ofc the markers remain

![image](https://user-images.githubusercontent.com/47384012/146737338-95fe68af-231f-4acd-ab08-0e4b080af4fe.png)

An I cannot access the path markers.

So I feel there is room for improvement:

-  `style_path_show=bool` would be cool to have
-  `style_path_line_style=''` this should really work
-  `style_path_line_style=':'` should be accepted as dotted
-  `style_path_line_width=0` should not show a line
-  `style_path_marker_size=0` should show no markers

**Comment by Alexboiboi** [comment]
I implemented most of it in a new branch https://github.com/magpylib/magpylib/tree/path_style

what should happen when `path=True` and `style_path_show=False`  in display? 
```python
import magpylib as magpy
s1 = magpy.magnet.Cuboid((0,0,1), (1,1,1), style_path_show=False)
s1.move([[1,0,0]]*10, increment=True)
s2 = magpy.magnet.Cuboid((0,0,1), (1,1,1), style_path_show=True)
s2.move([[0,1,0]]*10, increment=True)
magpy.display(s1, s2, backend='plotly', path=True, style_path_show=False,  style_path_line_style=':')
```

**Comment by Alexboiboi** [comment]
> `style_path_line_style=''`  this should really work

What should this do @OrtnerMichael ?
