### ISSUE TITLE
Bad matplotlib zoom window

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#441]
matplotlib `display()` now doesn't zoom properly when there is a path.

```
import numpy as np
import magpylib as magpy

s = magpy.magnet.Cuboid((0,0,1), (1,1,1))
s.move(np.linspace((0,0,0), (0,10,0), 10))
s.display()
```
Creates this figure

![image](https://user-images.githubusercontent.com/47384012/147393895-5ef32f35-afde-4db5-a6db-9f2625b9d7bd.png)

Plotly backend is doing the right thing

![image](https://user-images.githubusercontent.com/47384012/147393907-b663ce79-970b-48e3-a96a-0599a0b40329.png)

**Comment by Alexboiboi** [comment]
Is this a regression? How could we have missed this otherwise before

**Comment by OrtnerMichael** [comment]
must be - you solved this issue before as i remember

**Comment by Alexboiboi** [comment]
See #442 for more context
