### ISSUE TITLE
Renaming Collection.objects to Collection.children

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#446]
I startet to like more and more the idea to rename the `Collection.objects` into  `Collection.children`

yes / no / maybe ?

**Comment by Alexboiboi** [comment]
This was the idea originally but so far `objects` was prefered ;)

Is there maybe a good reason to keep track on the children level when it is added to a collection? the collection can then be called like `src.parent` ?

**Comment by Alexboiboi** [comment]
I would then also suggest to rename `set_styles` to `set_children_styles` to avoid any confusion with a possible `Compound` classes  (see #444)
In essence a `Collection` will never have its own `style` property but you can create it via  `Compound` class which in turn has a `style` property.

**Comment by OrtnerMichael** [comment]
I like the `set_children_styles` a lot - and also the idea that a Compound may have a style.

**Comment by Alexboiboi** [comment]
> `src.parent` sounds like a good idea. Will this be useful ?

If we want to prevent the user to add the same object to different collections for example

**Comment by Alexboiboi** [comment]
closed by #458
