### ISSUE TITLE
Plotly browser plot requires internet connection

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#447]
this is not so cool :)

**Comment by Alexboiboi** [comment]
I cannot reproduce this. For me it works without internet connection

**Comment by OrtnerMichael** [comment]
I will try to reproduce my plotly problem - in short: sometimes the browser seems blocked and displays nothing - stays on the loading screen.

**Comment by Alexboiboi** [comment]
can we close this?
