### ISSUE TITLE
Collection underscore magic

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#460]
Its a great feature to give all objects in a Collection a similar style, e.g. color.
this works (which is nice)

`col = Collection(sources, style=dict(color=x))`

but this does not work (which would be nicer and in-line with our library philosophy)

`col = Collection(sources, style_color=x)`

also this would be cool to work (not displaying magnetization for all Collection objects)

`col = Collection(sources, style_magnetization_show=False)`

the style hierarchy should be
**defaults < individual style < Collection style < show() kwargs**

**Comment by Alexboiboi** [comment]
fixed by 34344e7c9e2324b75c2baef104b4a72caa1fd23e
