### ISSUE TITLE
Collection Style behavior

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#461]
Since now Collection can have their own style it may be of interest to redefine the style hierarch:

**defaults < individual style < Collection style < show() kwargs**

also this would be cool to work (not displaying magnetization for all Collection objects)

`col = Collection(sources, style_magnetization_show=False)`

however there some weird behaviors that arise with this. So far, only the `color` style overrides individual `color` style. Does it make even sense to act in the same way with:
- `style_name`
- `style_description`
- `style_model3d`

I would tend to see the `Collection` as an object with its own style, independently from its children

**Comment by OrtnerMichael** [comment]
**feature1:** 
It feels logical that  `c1 = Collection(..., style_x)` applies `style_x` to all children.


**problem1**: which syle applies when objects are in multiple Collections ?
```
c1 = Collection(src, style_x)
c2 = Collection(src, style_y)
magpy.display(c1, c2)
```
