### ISSUE TITLE
Require scipy > 1.8 ? (drop python 3.7 support)

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#478]
As of scipy 1.8, the `scipy.spatial.transform.rotation` namespace is deprecated. The `Rotation` object is now to be found in `scipy.spatial.transform`. 

**Problem**:  `scipy>=1.8` requires python 3.8, so we would need to drop support for python 3.7 (see https://github.com/scipy/scipy/pull/14655)

@OrtnerMichael Should we require the minimum sicpy version to be 1.8 and rewrite the internal code where `Rotation` is imported?

**My Suggestion**: Lets leave it as is for the magpylib 4.0 version and we can always do this for 4.1 or even later.

(see https://github.com/scipy/scipy/issues/15572)

**Comment by rgommers** [comment]
> The `Rotation` object is now to be found in `scipy.spatial.transform`.

It was always there, see e.g. SciPy 1.6.3 docs: https://docs.scipy.org/doc/scipy-1.6.3/reference/spatial.transform.html#module-scipy.spatial.transform

So updating your code costs nothing, you don't have to drop support for older SciPy versions.

**Comment by Alexboiboi** [comment]
Hi @rgommers, thanks for pointing this out 

I was just getting deprectations errors when running the tests with scipy 1.8 because in some test files the old syntax was used. 

fixed by https://github.com/magpylib/magpylib/commit/67ee91380ceb141e627f648291e8339cb02b5058
