### ISSUE TITLE
Give CylinderSegment a "barycenter" attribute

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#480]
The problem is that the position attribute of the CylinderSegment is always in the center of the full cylinder.
```
import magpylib as magpy
s = magpy.magnet.CylinderSegment((0,0,1000), (1,2,1,0,20))
s.show(markers=[s.position], style_marker_symbol='o', style_marker_size=10)
```
![image](https://user-images.githubusercontent.com/47384012/155230654-4635b23b-70af-4e39-9b4f-4643cb838250.png)

When computing interactions or forces or torques we need the geometric center (should also be the start point of the magnetization arrow). Should we add a method `s.barycenter()` to this class ? Would make these computations much simpler.

**Comment by Alexboiboi** [comment]
closed by #484
