### ISSUE TITLE
[QUESTION] - How to customize the shape of Current object

### ISSUE THREAD

**Issue by ShannonZ** [magpylib/magpylib#481]
**Problem description**
[10.csv](https://github.com/magpylib/magpylib/files/8138326/10.csv)
![1](https://user-images.githubusercontent.com/7865691/155651101-0b62fa82-e8d5-44ab-80f8-d3e0cacad576.jpg)

How to simulate the magnetic field using the current stream field exported by other softwares?

**Comment by OrtnerMichael** [comment]
hi @ShannonZ

sorry for the late reply.

Your file includes of a set of vertices. Im not sure how to interpret this ? Are those line current segments ? If those are line current segments, then you can simply compute the field with `magpy.current.Line(vertices)`.

sincerely,
michael

**Comment by ShannonZ** [comment]
@OrtnerMichael This works. Thx for your reply.
