### ISSUE TITLE
Nesting Collection behavior

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#488]
Consider the following code:

```
x = magpy.Sensor()
coll = magpy.Collection(x)
super = magpy.Collection(coll)

# now moving super:
super.move((1,1,1))
```
**bad result:**
x.position is (1,1,1)
coll.position is (0,0,0)
super.position is (1,1,1)

`coll` was added to `super` but it did not move with it.

Following our *compound philosophy* i think that the `coll` collection base geo should have been manipulated !!!

**proposal**
- allow collections as children (maybe hidden ? maybe in a separate list ?)
- but these collection will be ignored for field computation

When this issue is fixed, fix the doku example: examples_03_collections.html

**Comment by Alexboiboi** [comment]
Are you sure about the [4.0](https://github.com/magpylib/magpylib/milestone/1) Milestone?

**Comment by OrtnerMichael** [comment]
**possible structure**

```
c1 = Collection(s1, s2)
c2 = Collection(s2, s3)
c3 = Collection(s4)
super = Collection(col1, col2, col3)

# add up collections and other objects in order, duplicates are not allowed.
print(super.sources) # out: s1, s2, s3, s4
print(super.children) # out: s1, s2, c1, s3, c2, s4, c3

# when removing an object, also remove all parents
super.remove(s1)
print(super.children) # out: s2, s3, c2, s4, c3

# when removing an object, also remove all children, unless they are inside another collection
super.remove(c2)
print(super.children) # out: s1, s2, c1, s4, c3

# when applying an operation to super, apply operation to BaseGeo of all children - must maintain compound geometry
super.position=(1,2,3)
print(c1.position) # out: (1,2,3)
```

**Comment by Alexboiboi** [comment]
I think if the new `Collection' behavior is a breaking change from the current 4.0.0 pre-release  we will have to delay again the release. If not, I'd suggest to move the implementation towards 4.0](https://github.com/magpylib/magpylib/milestone/1).

For now we just need to determine what are the breaking changes.

**Comment by OrtnerMichael** [comment]
**What do we want ?**

1. The current functionality that the collection just spans a local reference frame and holds some object references to that frame, which allows object manipulation through collection, but also by reference is really cool, easy to understand and practical (compound object parts tolerances)

2. Collections of collections are very practical when working with demag, complex objects, coils, compounds of compounds and so on. We really want to be able to bring a collection to another collection local reference frame ! Then we can manipulate the source, its collection and their super-collection and so on.

3. getBH of a source collection should give the field generated by this collection (incl. all sub-collections).

4. getBH of a sensor collection should give the field at every sensor -> Edge case: nested sensor collections

Everything else does not matter !

--> **How do we achieve this functionality ?**

- Object being part of multiple Collections ?
- Collection attributes e.g. `children`, `sources`, `sensors`, `collections` ?
- flat or tree structured ?
- same object multiple times in one collection ?
- behavior for adding and deleting objects to/from a Collection ?

**Comment by OrtnerMichael** [comment]
``` python
import magpylib as magpy

s1 = magpy.Sensor()
s2 = magpy.Sensor()

col = magpy.Collection(s1,s2)
COL = magpy.Collection(col)


COL.children # [col]

scol.sources     # []
scol.sensors     # []
scol.collections # [col]

scol.all_sources     # []
scol.all_sensors     # [s1,s2]
scol.all_collections # [col]

```
