### ISSUE TITLE
3D field line options - example code and pgk integration

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#494]
This is a really nice way to graphically represent the field. It should be added to the Coil example !!!!

- [ ] compare code options
- [ ] prepare nice coil example
- [ ] integrate into documentation
- [ ] consider as additional plotting option feature

![image](https://user-images.githubusercontent.com/47384012/158183338-f1610500-fd5c-4087-a2f8-a4bc3c4a8bbe.png)

**Comment by OrtnerMichael** [comment]
@peter-leitner can you please
1. describe the installation requirements
2. post a simple code example
3. post the output graphic

**Comment by OrtnerMichael** [comment]
@Alexboiboi can you do the same for plotly ? and then we see what is easier to handle and integrate ... maybe make an example out of both

**Comment by peter-leitner** [comment]
> @peter-leitner can you please
> 
> 1. describe the installation requirements
> 2. post a simple code example
> 3. post the output graphic

1.
> pip install --user pyvista or conda install pyvista should work
2. Here is a short code example showing field lines emanating from seed points on a sphere inside a coil with 20 windings, diameter = 2 cm around the z-axis from z = -2 cm ... z = +2 cm (see figure). The sphere is not plotted as it serves only as geometric location of seeding points such that the field lines appear axisymmetric on the plot.


`import numpy as np
import magpylib as magpy
import matplotlib.pylab as plt
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica"]})
from mpl_toolkits.mplot3d import Axes3D
offset = 100
phi = np.linspace(0, 2*np.pi, 100) # only for plotting coils in matplotlib
x = 20*np.cos(phi) # Cartesian coordinates of coils
y = 20*np.sin(phi)
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")
coil1 = magpy.Collection()
for z in np.linspace(-20,20,20):
    winding = magpy.current.Circular(current = 100,
                                     diameter = 20,
                                     position = (0,0,z))
    ax.plot(x,y,z,'r')
    coil1 += winding

ax.set_xlim(-30,30); ax.set_ylim(-30,30); ax.set_zlim(-30,30)
plt.show()

col = magpy.Collection(coil1)

# Here starts the VTK plotting stuff:
ctr = 0 # some counter
XYZlim = offset # mm; this defines the left-lower corner of the computational grid
Npoints = 30 # grid points for the B-field
B = np.zeros((Npoints,Npoints,Npoints,3))
for xi, x in enumerate(np.linspace(-XYZlim,XYZlim,Npoints)):
    for yj, y in enumerate(np.linspace(-XYZlim,XYZlim,Npoints)):
        for zk, z in enumerate(np.linspace(-XYZlim,XYZlim,Npoints)):
            B[xi,yj,zk,:] = col.getB((x,y,z))

# Extract the cartesian components:
Bx = B[:,:,:,0]
By = B[:,:,:,1]
Bz = B[:,:,:,2]

import pyvista as pv
grid = pv.UniformGrid() # generate a uniform cartesian grid
grid.dimensions = np.array(B.shape) + 1 # set its dimensions
grid.origin = (-offset,-offset,-offset) # define its origin and spacing
grid.spacing = (XYZlim*2/Npoints, XYZlim*2/Npoints, XYZlim*2/Npoints)
# Play the already computed cell data onto the grid:
grid.cell_data["Bx"] = Bx.flatten(order="F")
grid.cell_data["By"] = By.flatten(order="F")
grid.cell_data["Bz"] = Bz.flatten(order="F")
#slices = grid.slice_orthogonal(x=0,y=0,z=0) # do some slicing if you want
grid = grid.cell_data_to_point_data() # convert data that are already stored on the grid from cell centers to vertices
grid['B/mT'] = np.column_stack((grid.point_data['Bx'], grid.point_data['By'], grid.point_data['Bz'])) # set the B-field on the grid
# set the vector field active on the grid:
grid.set_active_vectors('B/mT')

p = pv.Plotter() # generate a new pyvista plotter
p.add_axes()
cpos = [(offset, offset, offset), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)] # camera position, focal point, view up
sargs = dict(height=0.2, vertical=True, title_font_size=30, width=0.05)

# Define a sphere and its surface resolution for seeding points
sphere = pv.Sphere(center=(0.0, 0.0, 0.0), radius=10.05, theta_resolution=13, phi_resolution=13)

# Compute streamlines emanating from sphere using vector-field "B/mT"
strl = grid.streamlines_from_source(sphere,vectors='B/mT',max_time=80.,initial_step_length=0.01, \
                                    integration_direction='both')

# Add the streamlines to the plotting scene:
p.add_mesh(strl.tube(radius=1), cmap="RdYlBu", scalar_bar_args=sargs)
p.show()`


![image](https://user-images.githubusercontent.com/51168238/161236038-6715ed59-c6c8-437f-b4f0-42810c70a837.png)
![image](https://user-images.githubusercontent.com/51168238/161236350-36d8bb05-085c-4d28-8d3f-e1bd0abe1468.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/51168238/161236976-ff27f0e0-7814-4d85-947f-010b805aadaa.png)

**Comment by Alexboiboi** [comment]
Hello Peter,

Thanks for your input ;) I allowed myself to rewrite your code to make it compatible with the latest magpylib version (v4) and also make it more minimalistic

```python
import numpy as np
import pyvista as pv
import magpylib as magpy

# Create winding
winding = magpy.Collection()
for z in np.linspace(-20, 20, 20):
    winding.add(magpy.current.Loop(current=100, diameter=20, position=(0, 0, z)))


# generate a uniform cartesian grid
offset = 100  # mm; this defines the left-lower corner of the computational grid
Npoints = 30  # grid points for the B-field
grid = pv.UniformGrid(
    dims=[Npoints] * 3, spacing=[offset * 2 / Npoints] * 3, origin=[-offset] * 3,
)
B = winding.getB(grid.points)

grid["B [mT]"] = B

# Define a sphere and its surface resolution for seeding points
sphere = pv.Sphere(
    center=(0.0, 0.0, 0.0), radius=10.05, theta_resolution=13, phi_resolution=13
)

# Compute streamlines emanating from sphere using vector-field "B/mT"
strl = grid.streamlines_from_source(
    sphere,
    vectors="B [mT]",
    max_time=80.0,
    initial_step_length=0.01,
    integration_direction="both",
)

p = pv.Plotter()  # generate a new pyvista plotter

# Add the streamlines to the plotting scene:
sargs = dict(height=0.2, vertical=True, title_font_size=30, width=0.05)
p.add_mesh(strl.tube(radius=1), cmap="RdYlBu", scalar_bar_args=sargs)
p.show()

# winding.show()
```
