### ISSUE TITLE
Binder Launcher pointing at development in Readme not working 

### ISSUE THREAD

**Issue by lucasgcbkhomp** [magpylib/magpylib#520]
### Magpylib version

3.x

### What happened?

Accessing the "Try it Out" binder in Readme for mybinder leads to a broken shell:
Link in readme: https://mybinder.org/v2/gh/magpylib/magpylib/development?filepath=docs%2Fexamples

![image](https://user-images.githubusercontent.com/101296102/163208400-89d3a54a-bd80-4105-9237-5a66d4e9f2aa.png)

### Code example

```Python
N/A
```

### Additional context

Swapping the link to the main branch makes the binder open, but I'm not sure how it should look like. The `?filepath=docs%2Fexamples` path query doesn't seem to load much for demonstrations.

 https://mybinder.org/v2/gh/magpylib/magpylib/main

**Comment by Alexboiboi** [comment]
Hi @lucasgcbkhomp, 

Thank you for pointing that out! This will be fixed in the upcoming official 4.0.0 release (probably tomorrow ;)) 

Cheers, Alex

**Comment by Alexboiboi** [comment]
> Swapping the link to the main branch makes the binder open, but I'm not sure how it should look like. The `?filepath=docs%2Fexamples` path query doesn't seem to load much for demonstrations.
> 
> https://mybinder.org/v2/gh/magpylib/magpylib/main

In the meantime you can try with the following link:

https://mybinder.org/v2/gh/magpylib/magpylib/4.0.0rc2?filepath=docs%2Fexamples

The landing page should be a jupyter file tree view where you can select example notebooks to run.

Unfortunately, it looks like mybinder.org is recently drastically limiting resources for building and launching environments.
