### ISSUE TITLE
setting color triples and quadruplets does not work

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#527]
### Magpylib version

4.x (Latest)

### What happened?

  File "c:\Users\ortner\Desktop\Magpylib4_dev\magpylib\__temp.py", line 5, in <module>
    cube.style.color=(.1,.2,.3)
  File "c:\Users\ortner\Desktop\Magpylib4_dev\magpylib\magpylib\_src\defaults\defaults_utility.py", line 345, in __setattr__
    object.__setattr__(self, key, value)
  File "c:\Users\ortner\Desktop\Magpylib4_dev\magpylib\magpylib\_src\style.py", line 147, in color
    self._color = color_validator(val, parent_name=f"{type(self).__name__}")
  File "c:\Users\ortner\Desktop\Magpylib4_dev\magpylib\magpylib\_src\defaults\defaults_utility.py", line 250, in color_validator
    color_input = f"#{c[0]:02x}{c[1]:02x}{c[2]:02x}"
ValueError: Unknown format code 'x' for object of type 'float'

### Code example

```Python
import magpylib as magpy
cube = magpy.magnet.Cuboid(magnetization=(0,0,1000), dimension=(20,10,1))

# this throws an error
cube.style.color=(.1,.2,.3)

# this is not implemented
cube.style.color=(.1,.2,.3,.4)
```

### Additional context

Some users might be used to providing colors as floats normalized from 0-1. We should add a warning when users attempt to do so that they have to provide integers 0-255.

Matplotlib users are used to coler formats in float - matplotlib cmaps will return float - quadruplets:

```
from matplotlib import pyplot as plt
cmap = plt.cm.get_cmap('jet')
print(cmap(.5))

# (0.4901960784313725, 1.0, 0.4775458570524984, 1.0)
```

**Comment by OrtnerMichael** [comment]
why is the color validator called called ca 30 times when I do the magpylib import ?

```
import magpylib as magpy
```

adding `print(color_input)` to `color_validator` returns this

None
None
None
None
None
None
None
None
None
None
None
None
None
None
#2e91e5
#e15f99
#1ca71c
#fb0d0d
#da16ff
#222a2a
#b68100
#750d86
#eb663b
#511cfb
#00a08b
#fb00d1
#fc0080
#b2828d
#6c7c32
#778aae
#862a16
#a777f1
#620042
#1616a7
#da60ca
#6c4516
#0d2a63
#af0038
None
None
None
#dddddd
#e71111
#00b050
None
grey
None
None
red
green
blue
None

**Comment by Alexboiboi** [comment]
> why is the color validator called called ca 30 times when I do the magpylib import ?

This is because `magpylib.defaults` are initialized at first import time and all properties containing color information get validated, also including all colors from the `magpylib.defaults.display.colorsequence`.
