### ISSUE TITLE
Source collection order bug

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#530]
### Magpylib version

4.x (Latest)

### What happened?

From @BillyTheKidPhysicist via Email:

... I have found that if I have a collection of sources and iterate through them as “for src in collection”, the order changed mid iteration if inside the loop I do “src.copy()”. I’ve attached code that reproduces this if you are interested. I may be misunderstanding something though, in which case disregard.

### Code example

```Python
from magpylib.magnet import Cuboid
from magpylib import Collection

thing1=Cuboid(magnetization=(1,0,0),position=(1,2,3),dimension=(5,5,5))
thing2=Cuboid(magnetization=(1,0,0),position=(10,2,3),dimension=(5,5,5))
thing3=Cuboid(magnetization=(1,0,0),position=(30,2,3),dimension=(5,5,5))
foo=Collection(thing1,thing2,thing3)
print(foo.sources_all)

#this has the expected order
print('expected--------')
for src in foo:
    print(src)

#That has unexpected order
print('different------')
for src in foo:
    src.copy()
    print(src)

#now this order has changed as well
print(foo.sources_all)
```

**Comment by Alexboiboi** [comment]
When copying a collection, we want to obtain an independent copy of it, but we don't want to copy objects upwards the tree structure, so we temporarily set the parent collection to `None` before.

https://github.com/magpylib/magpylib/blob/7c7e30e851bd01ee5ce804b37972f1ca3dde12bf/magpylib/_src/obj_classes/class_BaseGeo.py#L341-L345

L345 invokes the `parent` setter which retriggers the `.add()` method and in turns affects the order of the objects.

current fix @ https://github.com/magpylib/magpylib/tree/fix-copy-order-bug

https://github.com/magpylib/magpylib/blob/7b503dd13637bc83ab53e4fc166701665b0ded56/magpylib/_src/obj_classes/class_BaseGeo.py#L342-L347
