### ISSUE TITLE
⚠️ Pull request merge order

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#542]
Right now, quite a few changes in the library are happening at parallelly, and are often dependent on each other. In order not to loose track of these dependencies and the order in which they must me merged, I'll track this here.

Merge Order:

- [ ] #552 -> 4.3
- [ ] #549 -> 4.3 or Future

**Comment by OrtnerMichael** [comment]
@Alexboiboi  i think this can be closed?

**Comment by Alexboiboi** [comment]
No, i'll update it with the new branches
