### ISSUE TITLE
Inaccurate results when using small measurements for the z/y conductor

### ISSUE THREAD

**Issue by Blue-Spartan** [magpylib/magpylib#547]
### Magpylib version

4.x (Latest)

### What happened?

Hello, 
Currently, I am building a 3D Model that simulates an electromagnet. I begin by setting the measurements similar to what FEMM uses to calculate the magnetic field: inner_diameter, z_conductor, z_turns, x_conductor, x_turns, amps/current. 
From these values, I multiply the inner_diameter, z & x conductor by 1,000 to convert from Millitesla to Tesla units. I then create a box-like model, where each corner is labeled as X, Z to make the simulating easier (Check code below).
Afterward, I apply the NumPy- linspace to calculate/simulate the loops (using the current.Loop method). 
From there, I try to get the magnetic field around the inner diameter and coil by implementing X and Z coordinates to move around the coil. In return, I store the coordinates in a list to make it easier and faster to calculate getB once I have all the observers- but here's where getB begins acting strangely:
- When making the x_conductor to a smaller unit ( 0.001 -> 0.0001),  the magnetic field returns incorrect results compared to my other simulation software.

### Code example

```Python
from numpy import linspace
from magpylib import Collection, getB
from magpylib.current import Loop


# -----------------------------------------------------------------------------
'''User-defined measurements'''
# -----------------------------------------------------------------------------
inner_diameter = 0.1
z_conductor = 0.004 
z_turns = 10
'''
    THE STRANGE BEHAVIOR OCCURS WHEN I REDUCE THE X_COND TO A SMALLER UNIT
    Try adding another one or more zeros 
    and removing the round function at line 80 to view erro
'''
x_conductor = 0.001 
x_turns = 50
amps_current = 50
# -----------------------------------------------------------------------------
'''Switching from mT to T units'''
# -----------------------------------------------------------------------------
inner_diameter *= 1000
z_conductor *= 1000
x_conductor *= 1000
# -----------------------------------------------------------------------------
'''Similuating Coil'''
# -----------------------------------------------------------------------------
z_height = z_conductor * z_turns
outer_diameter = inner_diameter + 2 * (x_conductor * x_turns)

topLeftX = inner_diameter
topLeftZ = z_height * 0.5   
topRightX = outer_diameter
topRightZ = z_height * 0.5
bottomLeftX = inner_diameter
bottomLeftZ = z_height * -0.5
bottomRightX = outer_diameter
bottomRightZ = z_height * -0.5

# Linspace format arguments Z
startZ = bottomLeftZ + (0.5 * z_conductor)
endZ = topLeftZ - (0.5 * z_conductor)
numZ = z_turns

# Linspace format arguments X
startX = bottomLeftX + (x_conductor)
endX = bottomRightX - (x_conductor)
numX = x_turns

vertical = linspace(startZ, endZ, numZ)
horizontal = linspace(startX, endX, numX)

coil1 = Collection()

# Creating the coil lines vertically and horizontally
for z in vertical:
    for x in horizontal:
        winding = Loop(current = amps_current, diameter = x, 
                       position = (0, 0, z))
        coil1.add(winding)
# -----------------------------------------------------------------------------   
    '''Extracting Data From Coils'''
# -----------------------------------------------------------------------------
    observersXZ = []
    
    # Data from Inner Diameter- Moving Vertically
    coordx = 0.5 * topLeftX + (0.5 * x_conductor)
    coordz = topLeftZ - (0.5 * z_conductor)
    while coordz > bottomLeftZ:
        observersXZ += [[coordx, 0, coordz]]
        coordz -= z_conductor
        
        
    # Data from top of Coil (C) - horizontally
    coordxC = 0.5 * topLeftX + (0.5 * x_conductor)
    coordzC = topLeftZ - (0.5 * z_conductor)
    while coordxC < (topRightX / 2):
        
        # I need to round the x_coordinate or else I get a runtime warning
        observersXZ += [[round(coordxC, 2), 0, coordzC]]
        coordxC += x_conductor
    
    
    # Stores data returned from the coil1 (source) and observers
    # Division by 1000 to compare results with my other simulation software
    dataXZ = getB(coil1, observersXZ) / 1000 
    
    
    # Stores highest X, Z values; zero represents Y which is all zeros
    bmaxXMAG, zero, bmaxZMAG = dataXZ.max(axis=0)
# -----------------------------------------------------------------------------
'''END'''
# -----------------------------------------------------------------------------
```

### Additional context

OS: Windows 64 Bit
Spyder py3
The bottom bmax-Y is the correct value that I want to achieve.
![git](https://user-images.githubusercontent.com/106849143/179245150-b243f0cf-a7d0-4697-8804-a8d70b9227cf.png)

**Comment by Alexboiboi** [comment]
Hi @Blue-Spartan,

Thank you for your feedback!

I willing to help out, but I am not quite sure what you want to achieve here. 

1. From what I can see you are adding a series of Loops with each vertical increment. This means that, when calling the `getB` function on `coil1`, you are also including previous Loops incrementally. -> Not sure this is intended?

2. We have invested quite some efforts in visualization of Magpylib objects and their paths. I would recommend using these features to make sure, the sources and observers you are creating are in the correct places. It looks like the observers are the same for each vertical loop and are placed as below in the image (for the first loop only). -> Is this meant to be this sensor path?

<img width="671" alt="image" src="https://user-images.githubusercontent.com/29252289/179371344-0dd09b63-d72a-49a7-ac34-94f594f48c0d.png">

**Comment by Blue-Spartan** [comment]
Hello, thank you so much for replying. Is there any possible way to contact you privately? @Alexboiboi

**Comment by Blue-Spartan** [comment]
Hello again, I am reviewing the code you kindly sent here and the magpy.show method should show _**coil1**_, and not _**coils**_, as there is a number '1' at the end of the collection name; I am not sure if that was done intentionally. I again thank you for the time to review my code.
Below is a picture of the vertical loops. The code remains the same as the one I previously set, only this time, I set a break statement at the loop where the horizontal loops are created to visualize the Z axis better. 
The getB works fine when the x-conductor remains at 0.001, but as I decrease the measurement to 0.0001 or lower, the getB behaves strangely as explained. I am fairly new to magpy, as I've only experimented with the module for a few days now, so I am not confident with building 3D models, but I will dig deeper into sensors as you stated.

Best,
Jaden

<img width="582" alt="coilModel" src="https://user-images.githubusercontent.com/106849143/179374101-e93c45c0-aa70-472a-a6eb-035e6c52e1db.png">
<img width="558" alt="createVertical" src="https://user-images.githubusercontent.com/106849143/179374205-bdc236da-0f25-4774-b652-76963f46f0a6.png">

**Comment by Alexboiboi** [comment]
> Hello, thank you so much for replying. Is there any possible way to contact you privately? @Alexboiboi

Unless you need to share some sensitive information, I'd rather keep the discussion here, for future reference. ;)

Is there any good resaon your observers are directly on the coils?

**Comment by Blue-Spartan** [comment]
Hello @Alexboiboi,
I placed the observers directly in the coil to extract the magnetic field along the inner diameter, which seems to be the problem when extracting data with smaller measurements.

**Comment by Blue-Spartan** [comment]
1). Yes, I am trying to include the field from all loops.  The goal of this code is to simulate an electromagnet: each Loop represents a conductor/turn in the magnet.  The code should build a grid of Loops spaced apart by the conductor dimensions (x_conductor and z_conductor).

2) Yes, the observers appear to be in the correct location in your plot.  The observers are directly on the loops because I need to know the maximum field experienced by the conductor itself.  The entire coil (all Loops) should contribute to the magnetic field at the observer locations.  The ultimate goal is to obtain the maximum X and Z fields experienced in the conductor: peak Z-field should occur along the innermost turns/Loops (the vertical line of observers), while peak X-field should occur along the topmost turns/Loops (horizontal line of observers).   As mentioned, the above code gets the correct values when the size of the conductor in the X direction (x_conductor) is 0.001 (1mm).  When set to 0.0001 (0.1mm), the code seems to give incorrect Z-field values (about double/triple what they should be).

**Comment by Alexboiboi** [comment]
I think you provided enough infos, thanks.

Quite some effort has been put into numerical stability of line current computation and the possibility remains that the FEM calculation may be wrong.

@OrtnerMichael  can you look into this please ? Thanks

**Comment by OrtnerMichael** [comment]
hey @Blue-Spartan 

so there are a bunch of reasons you might get a bad result

1. with FEMM you are simulating a 3D model. Do you simulate it as a solid body or as a homogeneous current distribution ?
--> Assuming case 2 (homogeneous current)

2. with Magpylib your are approximating a homogeneous current distribution by a lot of current filaments. This is from the start not a good approach when you are interested in the field very close to the conductor, because the individual windings and their packing order will locally distort the field. Specifically when you approach the surface closer than the distance between two windings you will get completely different results.
--> Assuming your FE model includes all the individual windings (not a homogeneous body in FEMM)

3. There is a numerical instability in Magpylib when approaching the current filament. You can easily make it visible by approaching the loop closer than 1e-8 times its radius (see figure below). The reason lies simply with the employed expression for the magnetic field computation. (cel algorithm just breaks down when approaching the singularity). We are actually working to improve that in version 4.1

![image](https://user-images.githubusercontent.com/47384012/179613360-6bf572e1-162d-462a-9563-4c3acf1c9631.png)

But you should see this behavior in both field components and not just with Bz.

If this doesn't explain your issues - please provide a **minimal code example** where the field of a `magpy.current.Loop` object is computed and gives a wrong result.

sincerely

**Comment by Blue-Spartan** [comment]
Thank you for the help and insight.  Your summary is correct, FEMM is modeled as a homogeneous current distribution.  I agree it is not ideal to model this via current filaments in magpylib  It seems the numerical instability may be causing issues for small x_conductor.  Is there a better way to model what I am trying to do in magpylib, or is the grid of Loops the only approach?

**Comment by OrtnerMichael** [comment]
hi @Blue-Spartan 

In Magpylib there is only this approach. However, you must understand that your Magpylib model is more accurate than the FE model at close distance. When you construct coils, you always have the packing problem of the individual windings

![image](https://user-images.githubusercontent.com/47384012/179723610-871ece82-319d-4c77-a30b-faf1433bbee7.png)

Each winding generates a field that is accurately described by the current filament (on the outside of the winding wire). So if properly arranged, Magpylib Loops are a more accurate model than the homogeneous current computed by FEMM.

I must confess, that I'm a bit surprised that the loss of accuracy is so bad. With current implementations you will only be able to approach the filament with `10^-6 * radius` to be on the safe side. However, I am also a bit surprised this is not good enough for you. This means that you can model correctly a coil with a !!! 1 meter radius !!! made of windings with only !!! 2 micron thick !!! wire.

To you have something more extreme than this ?

You are aware that the field of a filament coincides with the field of a wire with circular cross section only on the outside of the real wire ?

sincerely,
michael

**Comment by Alexboiboi** [comment]
For future Reference, a way to create a Compound object with windings.

```python
import magpylib as magpy
import numpy as np


class Windings(magpy.Collection):
    def __init__(
        self,
        inner_radius=1,
        outer_radius=2,
        height=1,
        density=(2, 2),
        current=1,
        **style_kwargs,
    ):
        super().__init__(**style_kwargs)
        self.update(
            inner_radius=inner_radius,
            outer_radius=outer_radius,
            height=height,
            density=density,
            current=current,
        )

    def update(self, **kwargs):
        for k, v in kwargs.items():
            if k in ("inner_radius", "outer_radius", "height"):
                setattr(self, f"_{k}", self._validate_scalar(v, k, positive=True))
            elif k == "density":
                setattr(self, f"_{k}", self._validate_density(v))
            elif k == "current":
                setattr(self, f"_{k}", self._validate_scalar(v, k))

        self._inner_radius, self._outer_radius = sorted(
            (self._inner_radius, self._outer_radius)
        )
        self._update_loops()

    def _update_loops(self):
        loops = []
        for r in np.linspace(self._inner_radius, self._outer_radius, self._density[0]):
            for h in np.linspace(-self._height / 2, self._height / 2, self._density[1]):
                loop = magpy.current.Loop(self._current, r * 2, position=(0, 0, h))
                loop.rotate(self._orientation, anchor=0, start=0)
                loop.move(self._position, start=0)
                loops.append(loop)
        self.children = loops

    @staticmethod
    def _validate_scalar(val, key, positive=False):
        from numbers import Number

        if not (isinstance(val, Number) and (val >= 0 or not positive)):
            raise ValueError(f"{key} must be a positive number, received {val} instead")
        return val

    @staticmethod
    def _validate_density(val):
        failed = False
        try:
            val = np.array(val, dtype=int)
        except (TypeError, ValueError):
            failed = True
        if not failed:
            failed = val.shape != (2,)
        if not failed:
            failed = any(v <= 0 for v in val)
        if failed:
            raise ValueError(
                f"'density' must be 2 positive integers, received {val} instead"
            )
        return tuple(val)

    @property
    def height(self):
        return self._height

    @height.setter
    def height(self, val):
        self.update(height=val)

    @property
    def inner_radius(self):
        return self._inner_radius

    @inner_radius.setter
    def inner_radius(self, val):
        self.update(inner_radius=val)

    @property
    def outer_radius(self):
        return self._outer_radius

    @outer_radius.setter
    def outer_radius(self, val):
        self.update(outer_radius=val)

    @property
    def density(self):
        return self._density

    @density.setter
    def density(self, val):
        self.update(density=val)

    @property
    def current(self):
        return self._current

    @current.setter
    def current(self, val):
        for child in self.sources:
            child.current = val
```

Possible use:

```python
w = Windings(inner_radius=4, outer_radius=8, height=2, density=(3, 3))
pixel = [[x, 0, z] for x in np.linspace(-2, 2, 7) for z in np.linspace(-1, 1, 5)]
sens = magpy.Sensor(pixel=pixel)
B = w.getB(sens)
print(B)
magpy.show(w, sens, backend="plotly")
```
![image](https://user-images.githubusercontent.com/29252289/179743074-676089ce-b6fc-4977-a374-743f70292fa8.png)


or with path:

```python
w = Windings(inner_radius=4, outer_radius=8, height=2, density=(3, 3))
w.rotate_from_angax(np.linspace(0, 20, 3), "x", anchor=(0, 50, 0), start=0)
w.density = (5, 3)
magpy.show(w, backend="plotly", style_path_frames=1)
```
![image](https://user-images.githubusercontent.com/29252289/179743269-c07a391a-7a25-4872-ad01-320658801ea3.png)

**Comment by Blue-Spartan** [comment]
@OrtnerMichael
I believe the packing problem is not an issue in my case because my wire has a rectangular cross-section instead of round.  The turns pack very nicely together, with nearly 100% fill.  This should make the homogeneous current distribution reasonably accurate, correct?
 
If the 1 meter radius and 2 micron thick wire limitations are correct, that is more than enough for my application.  I am interested in perhaps 1 meter radius and 100 micron wire.  If loss of accuracy is not the issue, what is causing the Z-fields to match FEMM for 1x4mm conductor, but not for 0.1x4mm conductor?  Is it the aspect ratio of the rectangular conductor: the thinner (x-dimension) and taller (z-dimension) the conductor, the less relevant a Loop approximation will be? 
 
When the observers located precisely at the Loop coordinates (center of conductor) were unexpectedly high, I tried putting the observers at the corner of the conductor dimensions.  The fields were still higher than expected, albeit less so (maybe 2x). 
 
@Alexboiboi
Thank you for compound object winding example

**Comment by OrtnerMichael** [comment]
He @Blue-Spartan 

I this case you are right, the homogeneous current distribution is a better model than a superposition of a lot of small wires.

In principle the superposition will then still work, but the results will be wrong once you compute the field close to the 'surface'. Close means same order of magnitude or less as the chosen wire spacing. I guess this is what happens in your case. If you want to have a correct result close to the conductor, you have to increase the "wire density" - but this will require a lot of computation power and is not a good ansatz.

Why do you want to compute this ?
Why switch from FEMM to Magpylib ? Want to create a real 3D model ?

sincerely,
Michael

**Comment by Blue-Spartan** [comment]
Hello @OrtnerMichael,
Yes, I am looking for alternatives to FEMM largely to be able to simulate more complex 3d coil designs.  The simple solenoid calculations were just a starting point.

**Comment by Alexboiboi** [comment]
I'm closing this, feel free to reopen the issue in case it becomes relevant again.
