### ISSUE TITLE
Docu: Make rotation anchor more visible in documentation

### ISSUE THREAD

**Issue by laikh** [magpylib/magpylib#564]
### Describe the feature you'd like

when you google for magpylib rotation you find an exmaple from magpylib 2

in doku do not use anchor=0, use anchor=(0,0,0)

refer/explain anchor rotation VS orientation better in docu !!!

its a bit confusing

**Comment by OrtnerMichael** [comment]
comes with the next update in 2022

**Comment by Alexboiboi** [comment]
Will this really be fixed in 4.2 or we push it further?
