### ISSUE TITLE
TriangularMesh

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#569]
Discussion how the FacetBody class should look like.

TBD

from previous posting:

### The FacetBody class

This class should be quite similar to the TriangularMesh class that @Alexboiboi introduced in the original facet branch, but it is still work in progress and features should still be discussed. The idea is that triangular meshes can be handed over easily, that inside-outside checks will be performed by default ( but can be turned off), and that facet orientation is automatically fixed by default (but can also be turned off).

Parameters: magnetization (the usual) and vertices shape (n,3) and triangles shape (n,3)

It seems to be the common choice in defining meshes through a list of unique vertices, and a second list of indices that define the cells. This is done in pyvista, scipy, pymesh, gmesh, ... . Since we already used vertices in other classes I would use this again for the points, and I really like triangles for the index list.

- pymesh.Mesh uses a list of unique vertices called vertices and a list of face index triplets called faces, supporting triangles and quad faces.
- pyvista.PolyData objects use a list of unique vertices called points and a 1D array [3, 1, 2, 3, 3, 2, 3, 4, ...] called faces where the bold number indicates how many indices define the next face. This enables non-triangular meshes.
- scipy.spatial.Delauny uses a list of vertices called points and a list of face index triplets (like PyMesh) called simplices. The points are not unique.

**Comment by Alexboiboi** [comment]
Current work at https://github.com/magpylib/magpylib/tree/facet_body
Tasks
- [x] Field functions
- [x] graphical implementation
- [ ] class naming `FacetBody` or `TriangularMesh`
- [ ] robust closed body check, if implemented (Euler–Poincaré characteristic is insufficient) 
- [x] Object interface
- [x] check `getBH` (inside/outside)
- [x] optional automatic reorienting facets
- [ ] optional check if closed mesh
- [ ] optional check if self intersect

Other tasks
- [ ] docstrings (+ examples)
- [ ] tests
- [ ] changelog
- [ ] docs with examples

**Comment by OrtnerMichael** [comment]
@Alexboiboi I played a bit around with `TriangularMesh`, started to go through your code and here are a few points that we need to discuss before I start changing/implementing anything

## Which inputs and which names

I think the information that defines the `TriangularMesh()` should be collected in two attributes `points/vertices` shape (n,3) and denoting unique vertices, and in `triangles/facets/faces/simplices` shape (m,3) type int to denote the triangles.
 - I would vote for `vertices` for consistency with other classes.
 - I would vote for `triangles` because its most descriptive.

We should consider if the representation in shape (n,3,3), currently termed `facets` and originally used for the `Facet` class, should be included at all. I think I'm against it, at best we should provide a method `export_faces` ... but better not since its just a single numpy command: `np.take(vertices, triangles, axis=0)`.

I think both `vertices` and `triangles` should be parameters.

I'm strongly against the use of `scipy..ConvexHull()`. When a user wants to do that, he should, but that's not our problem and we should really avoid adding "features" that are solved with one-liners, especially not when this adds 100 lines to our code !

What I think could make sense is some function/method `generate_from_pyvista(PolyData object)` because pyvista stores the mesh a bit differently, but such a feature has to be discussed, as in the end it would just be
```
vertices = pv_obj.points
triangles = pv_obj.faces.reshape(-1,4)[:,1:]
```

# to be continued after lunch

**Comment by OrtnerMichael** [comment]
**Discussion @OrtnerMichael and @Alexboiboi :**

1. Facets out
2. `vertices` and `triangles` should be attributes without setters !
3. import from other libraries using class methods TBD
   a. `from_pyvista` given a pyvista PolyData object
   b. `from_points` given points and using scipy..ConvexHull

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael,

The changes I could implement are now up to date with test (100% coverage). Waiting for feedback.

The styling topic is mostly independent, and I'll continue to work on in in another branch

**Comment by OrtnerMichael** [comment]
@Alexboiboi 

Looks great - everything works as discussed !
Also i like the classmethods of TriangulaMesh
```
import pyvista as pv
import magpylib as magpy
magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(1,2,3),
    polydata=pv.Text3D("I'm loving it")
).show(backend='pyvista')
```
![image](https://user-images.githubusercontent.com/47384012/216614370-bb58709d-37ec-47da-aac6-4660478ece61.png)

I'll check and work on the methods face_flip, inside_outside, closed_mesh, separate_bodies, and also to clean up e.g. checks that are in the TriangularMesh class ... not sure if they should be there... and maybe start working on the docstrings.

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael ,

I have updated the style structure to allow for composition. The `TriangularMesh` object can now define its own defaults and fall back to the `Magnet` style. I added some mesh visualization features such as `open` and `intersect` properties (see example below). I also drafted a `disjoined` mesh style property but I am waiting for your branch to be merged in order to use your validation code for it ;)

Can you check it out?

```python
import numpy as np
import magpylib as magpy

self_intersecting_mesh3d = {
    "x": [-1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 0.5],
    "y": [-1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 0.1],
    "z": [-1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -2.0],
    "i": [7, 0, 0, 0, 2, 6, 4, 0, 3, 7, 4, 5, 6, 7],
    "j": [0, 7, 1, 2, 1, 2, 5, 5, 2, 2, 5, 6, 7, 4],
    "k": [3, 4, 2, 3, 5, 5, 0, 1, 7, 6, 8, 8, 8, 8],
}
vertices = np.array([v for k, v in self_intersecting_mesh3d.items() if k in "xyz"]).T
triangles = np.array([v for k, v in self_intersecting_mesh3d.items() if k in "ijk"]).T

triangles = triangles[1:]  # open the mesh

trimesh = magpy.magnet.TriangularMesh(
    magnetization=(0, 0, 1000),
    vertices=vertices,
    triangles=triangles,
    validate_mesh=False,
    reorient_facets=False,
)
trimesh.style.mesh.intersect.marker.size = 15
trimesh.style.mesh.intersect.line.color = "orange"
trimesh.show(style_opacity=0.5, backend="plotly")
```
![image](https://user-images.githubusercontent.com/29252289/217233702-63896bd2-0412-423a-a567-592362accde8.png)

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael,

I have done some basic profiling of the implemented mesh validation algorithms (also including self-intersection). 
In short, the reorientation of facets is by far the most time consuming operation when having lots of facets (self-intersection is in the same order)

<img width="763" alt="image" src="https://user-images.githubusercontent.com/29252289/220361666-3e92139c-d699-42cd-921b-45768af1b522.png">

### To reproduce
```python
from time import perf_counter

import numpy as np
import pandas as pd
import plotly.express as px
import pyvista as pv
from magpylib._src.fields.field_BH_triangularmesh import (
    fix_trimesh_orientation,
    get_disjoint_triangles_subsets,
    trimesh_is_closed,
)


def signed_volume(a, b, c, d):
    """Computes the signed volume of a series of tetrahedrons defined by the vertices in
    a, b c and d. The ouput is an SxT array which gives the signed volume of the tetrahedron
    defined by the line segment 's' and two vertices of the triangle 't'."""

    return np.sum((a - d) * np.cross(b - d, c - d), axis=2)


def segments_intersect_triangle(segments, facets, summation=True):
    """For each line segment in `segments`, this function computes how many times it intersects
    any of the facets given in `facets`.

    Parameters
    ----------
    segments: Sx2x3 array
        Array of `S` line segments where the first index specifies the S^th line segment, the
        second index refers to the start or end point of the segment, and the third index points
        to the x, y, z coordinates of the line segment point.

    facets: Tx3x3
        Array of `T` triangular facets, where the first index specifies the T^th triangle, the
        second index refers to one of the three vertices (which don't have to be in any particular
        order), and the third index points to the x,y,z coordinates the the triangle vertex.

    summation: bool, optional
        If `True`, a binary array is return which only tells if the S^th line segment intersects
        any of  the facets given. If `False`, returns a SxT array that tells which facets are
        intersected.

    Returns
    -------
        If `'summation'` is `True`, returns a binary array of size S which tells whether the S^th
        line segment intersects any of the facets given. Otherwise returns a SxT array that tells
        which facets are intersected.
    """

    s, t = segments, facets
    # compute the normals to each triangle
    normals = np.cross(t[:, 2] - t[:, 0], t[:, 2] - t[:, 1])
    normals /= np.linalg.norm(normals, axis=1, keepdims=True)

    # get sign of each segment endpoint, if the sign changes then we know this segment crosses the
    # plane which contains a triangle. If the value is zero the endpoint of the segment lies on the
    # plane.
    s0, s1 = s[:, :1], s[:, 1:]  # -> S x T x 3 arrays
    sign1 = np.sign(np.sum(normals * (s0 - t[:, 2]), axis=2))  # S x T
    sign2 = np.sign(np.sum(normals * (s1 - t[:, 2]), axis=2))  # S x T

    # determine segments which cross the plane of a triangle.
    #  -> 1 if the sign of the end points of s is
    # different AND one of end points of s is not a vertex of t
    cross = (sign1 != sign2) * (sign1 != 0) * (sign2 != 0)  # S x T

    # get signed volumes
    v = [
        np.sign(signed_volume(t[:, i], t[:, j], s0, s1))
        for i, j in zip((0, 1, 2), (1, 2, 0))
    ]  # S x T
    same_volume = np.logical_and(
        (v[0] == v[1]), (v[1] == v[2])
    )  # 1 if s and t have same sign in v0, v1 and v2

    res = cross * same_volume
    if summation:
        res = np.sum(res, axis=1)

    return res

def check_self_intersection(triangles):
    edges = np.concatenate(
    [triangles[:, 0:2], triangles[:, 1:3], triangles[:, ::2]], axis=0
    )
    edges_uniq, edges_counts = np.unique(
        np.sort(edges, axis=1), axis=0, return_counts=True
    )
    facets = vertices[triangles]
    segments = vertices[edges_uniq]
    return segments_intersect_triangle(segments, facets)


def time_it(func, *args, **kwargs):
    start = perf_counter()
    func(*args, **kwargs)
    return perf_counter() - start


res = {"reorient": [], "check closed": [], "check connected": [], "check self-intersection": []}
tri = []
for i in range(6):
    polydata = pv.Tetrahedron()
    if i > 0:
        polydata = polydata.subdivide(i)
    for j in range(2):
        polydata = polydata.triangulate()
        polydata = polydata.merge(pv.Tetrahedron(center=(10*j, 0, 0)).triangulate())
        vertices = polydata.points
        triangles = polydata.faces.reshape(-1, 4)[:, 1:]
        tri.append(len(triangles))
        res["reorient"].append(time_it(fix_trimesh_orientation, vertices, triangles))
        res["check closed"].append(time_it(trimesh_is_closed, triangles))
        res["check connected"].append(time_it(get_disjoint_triangles_subsets, triangles))
        res["check self-intersection"].append(time_it(check_self_intersection, triangles))
res
df = pd.DataFrame(res)
df["triangles"] = tri
print(df)

fig = px.line(
    df,
    x="triangles",
    y=res,
    #facet_col="variable",
    labels={"value": "time (s)"},
    log_x=True,
    log_y=True,
    facet_col_spacing=0.05,
)
fig.update_yaxes(showticklabels=True)
fig.show()
```

**Comment by Alexboiboi** [comment]
Should we add a method `to_collection` to distribute disjoint parts into children of a collection? What do you think?

**Comment by Alexboiboi** [comment]
With the help of the `.clean()` method it is possible to get rid of the "disconnected" problem, but the mesh remains open...

```python
import pyvista as pv
import magpylib as magpy

# create a complex pyvista PolyData object
sphere = pv.Sphere(radius=0.85)
dodec = pv.Dodecahedron().triangulate()
obj = dodec.boolean_difference(sphere)
obj = obj.clean()
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(0,0,100),
    polydata=obj,
    validate_connected=False,
    validate_closed=False,
    reorient_triangles=False,
    style_label="Dodecahedron cut by Sphere",
)

magnet.show(backend='plotly')
```
<img width="687" alt="image" src="https://user-images.githubusercontent.com/29252289/222497629-54118d3d-6701-45fa-b68f-d08639251793.png">


```python
import magpylib as magpy
import pyvista as pv

# create a complex pyvista PolyData object
cyl = pv.Cylinder(radius=0.4, height=2).triangulate()
cyl = cyl.rotate_y(-30)
dodec = pv.Dodecahedron().triangulate()
obj = dodec.boolean_difference(cyl)
obj = obj.clean()
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(0, 0, 100),
    polydata=obj,
    validate_connected=False,
    validate_closed=False,
    reorient_triangles=False,
    style_label="Dodecahedron cut by Cylinder",
)

magnet.show(backend="plotly")
```
<img width="681" alt="image" src="https://user-images.githubusercontent.com/29252289/222497724-64e2d277-660e-4d33-8e56-0c5d6d6c63cb.png">

```python
import magpylib as magpy
import pyvista as pv

# create a complex pyvista PolyData object
cube = pv.Cube(x_length=0.5, y_length=0.5, z_length=3).triangulate()
cube = cube.rotate_x(30)
dodec = pv.Dodecahedron().triangulate()
obj = dodec.boolean_difference(cube)
obj = obj.clean()
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(0, 0, 100),
    polydata=obj,
    validate_connected=False,
    validate_closed=False,
    reorient_triangles=False,
    style_label="Dodecahedron cut by Cuboid",
)

magnet.show(backend="plotly")
```
<img width="682" alt="image" src="https://user-images.githubusercontent.com/29252289/222497851-eb9bb96d-1184-4228-a303-df1f180d71ed.png">

**Comment by Alexboiboi** [comment]
And with the `.subdivide()` method applied to the dodecahedron it makes a clean mesh ;)

```python
import pyvista as pv
import magpylib as magpy

# create a complex pyvista PolyData object
sphere = pv.Sphere(radius=0.85)
dodec = pv.Dodecahedron().triangulate().subdivide(2)
obj = dodec.boolean_difference(sphere)
obj = obj.clean()
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(0,0,100),
    polydata=obj,
    validate_connected=False,
    validate_closed=False,
    reorient_triangles=False,
    style_label="Dodecahedron cut by Sphere",
)

magnet.show(backend='plotly')
```
<img width="659" alt="image" src="https://user-images.githubusercontent.com/29252289/222499666-f36ee266-71cc-4254-a410-de8a520e68fd.png">

```python
import magpylib as magpy
import pyvista as pv

# create a complex pyvista PolyData object
cyl = pv.Cylinder(radius=0.4, height=2).triangulate()
cyl = cyl.rotate_y(-30)
dodec = pv.Dodecahedron().triangulate().subdivide(2)
obj = dodec.boolean_difference(cyl)
obj = obj.clean()
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(0, 0, 100),
    polydata=obj,
    validate_connected=False,
    validate_closed=False,
    reorient_triangles=False,
    style_label="Dodecahedron cut by Cylinder",
)

magnet.show(backend="plotly")
```
<img width="622" alt="image" src="https://user-images.githubusercontent.com/29252289/222499773-01415c91-d4b4-4129-9ce6-93d046c0cf04.png">


```python
import magpylib as magpy
import pyvista as pv

# create a complex pyvista PolyData object
cube = pv.Cube(x_length=0.5, y_length=0.5, z_length=3).triangulate()
cube = cube.rotate_x(30)
dodec = pv.Dodecahedron().triangulate().subdivide(2)
obj = dodec.boolean_difference(cube)
obj = obj.clean()
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=(0, 0, 100),
    polydata=obj,
    validate_connected=False,
    validate_closed=False,
    reorient_triangles=False,
    style_label="Dodecahedron cut by Cuboid",
)

magnet.show(backend="plotly")
```

<img width="641" alt="image" src="https://user-images.githubusercontent.com/29252289/222499955-40142821-a965-494a-897e-739324005f6f.png">

**Comment by OrtnerMichael** [comment]
hi @Alexboiboi 

1. Great that you managed to improve the algorithms ! Feel free to replace your/my old ones any time.
2. Concerning pyvista meshes from boolean operations: this looks like a lot of good and important know-how that should go to the documentation !

Do you see any other problems when creating complex shapes with pyvista ?

Can I review the trimesh body branch ?

**Comment by Alexboiboi** [comment]
U can review the branch, I may just edit som visualization features

**Comment by Alexboiboi** [comment]
To summarize the current validation performance:
With 10^4 triangles, validation takes approx 1 sec.
```python
from time import perf_counter

import magpylib as magpy
import numpy as np
import pandas as pd
import plotly.express as px
import pyvista as pv
from magpylib._src.fields.field_BH_triangularmesh import (
    fix_trimesh_orientation,
    get_disjoint_triangles_subsets,
    trimesh_is_closed,
)


def time_it(func, *args, **kwargs):
    start = perf_counter()
    func(*args, **kwargs)
    return perf_counter() - start

inputs = {
    "reorient": {"func": fix_trimesh_orientation, "names": ("vertices", "triangles")},
    "validate closed": {"func": trimesh_is_closed, "names": ("triangles",)},
    "validate connected": {"func": get_disjoint_triangles_subsets, "names": ("triangles", )},
}
results=[]
tri = []
for resol in [ 3, 4, 5, 6, 9, 15, 22, 28, 34, 41, 47, 53, 60, 67, 75]:
    resol = int(resol)
    polydata = pv.Sphere(phi_resolution=resol, theta_resolution=resol).triangulate()
    vertices = polydata.points
    triangles = polydata.faces.reshape(-1, 4)[:, 1:]
    print(f"batch with {len(triangles)} triangles")
    kwargs = {"triangles": triangles, "vertices": vertices}
    for name, val in inputs.items():
        t = time_it(val["func"], **{k:v for k,v in kwargs.items() if k in val["names"]})
        res = {"name": name, "time": t, "triangles": len(triangles)}
        print(res)
        results.append(res)

df = pd.DataFrame(results)

df["num of triangles"] = df["triangles"].astype(str) + " "
df["time [ms]"] = df["time"]*1000
fig = px.bar(
    df,
    x="num of triangles",
    y="time [ms]",
    # facet_col="variable",
    color="name",
    #log_x=True,
    log_y=True,
    facet_col_spacing=0.05,
    barmode="stack", # ['stack', 'group', 'overlay', 'relative']
)
fig.show()
```
<img width="877" alt="image" src="https://user-images.githubusercontent.com/29252289/222927656-a059a3e3-e915-4877-9931-577fe90b8cf8.png">

**Comment by Alexboiboi** [comment]
to test some memory issue: 
- see #600 

```python
import magpylib as magpy
import matplotlib.pyplot as plt
import numpy as np
import pyvista as pv

Nt = 10000 # target number of triangles
r = int(np.sqrt(Nt/2))
sphere  = pv.Sphere(theta_resolution=r, phi_resolution=r)
magnet = magpy.magnet.TriangularMesh.from_pyvista(
    magnetization=[0, 100, 0],
    polydata = sphere,
)

N = 30
xs = np.linspace(-1e3, 1e3, N)
ys = np.linspace(0, 1e3, N)
grid = np.array([[(x, y, 0) for x in xs] for y in ys])

%%time

Np = np.prod(grid.shape[:-1]) # number of points
Ns = 100  # number of subsets
slices = [slice(i * Np // Ns, (i + 1) * Np // Ns) for i in range(Ns)]

B = np.concatenate(
    [magpy.getB(magnet, grid.reshape(-1,3)[sl]) for sl in slices]
).reshape(grid.shape)

%%time

B1 = magpy.getB(magnet, grid)

np.testing.assert_allclose(B, B1)
```

**Comment by OrtnerMichael** [comment]
this is completed with #598
