### ISSUE TITLE
MagLib - A Fortran-based core

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#579]
We are aiming for a new computational core. the reason is, that numpy is fast when arrays are large, but slow when they are not. After careful consideration we believe that Fortran is the way to go. We are currently trying to finance the development of a separate Fortran package that functions as the new Magpylib core.

Topics/Tasks to be addressed are:

1. Computation performance
2. Numerical stability
3. FEM tests to all core functions
4. Source distribution -> Built distribution

**Comment by purepani** [comment]
Hello! I was just wondering why the choice of fortran over C?

**Comment by OrtnerMichael** [comment]
He @purepani 

In terms of performance it will make little difference, and we have someone who is good with Fortran.
Also Nim and Cython are options...but currently we tend to using Fortran which was made for technical applications like ours.

**Comment by OrtnerMichael** [comment]
this can be closed based on discussion with @fspacheco 
At this point we will not move from Numpy to a Fortran or C-based core

**Comment by purepani** [comment]
Nice! Is there a discussion I can read somewhere? I'm mostly interested in how this decision was reached(I feel like I learn a lot from reading those types of discussions).
Maybe the new array api standard/numpy about to move to 2.0 are part of the reasons?

**Comment by purepani** [comment]
Nice! Is there a discussion I can read somewhere? I'm mostly interested in how this decision was reached(I feel like I learn a lot from reading those types of discussions).
Maybe the new array api standard/numpy about to move to 2.0 are part of the reasons?

**Comment by OrtnerMichael** [comment]
he @purepani 

the discussion is here #668 

Long story short: Not worth it in terms of effort VS gain (which is probably minial) and loss of code/flow readability)

**Comment by purepani** [comment]
Makes sense! In that case, maybe it makes sense to support using the new array api standard that numpy 2.0 is using. That way users can use whatever arrays they want as long as it supports it. It would be less effort than rewriting in a low level language and offers the benefits of speedups and interoperability with any array type.
