### ISSUE TITLE
Rotating collection behaves different than rotating a single magnet

### ISSUE THREAD

**Issue by 9Volts9er** [magpylib/magpylib#583]
### Magpylib version

4.x (Latest)

### What happened?

I'm combining two rotations (around x and around z). For the rotation around z I'm using an anchor point.
If I apply those rotations to a normal Cylinder magnet, it does exactly what I expected: It rotates around x of the magnet, and around Z of the anchor point.
But as soon as I apply the same `rotate_from_angax()` to a Collection of two it follows a different path: Now it also moves down (in negative z-direction).

The code example below shows this behavior. `magnetCol` is moving strangely, but `magnet` does what I would have expected.

### Code example

```Python
import magpylib as magpy
import matplotlib.pyplot as plt
import numpy as np

magnet1 = magpy.magnet.Cylinder(magnetization=(1200, 0, 0), dimension=(16, 6), position=(0, 0, 8))
magnet2 = magpy.magnet.Cylinder(magnetization=(-1200, 0, 0), dimension=(8, 6), position=(0, 0, 8))
magnetCol = magpy.Collection(magnet1, magnet2)

angles = np.linspace(0, 180, 100)

magnetCol.rotate_from_angax(angles, axis='x', start=0)
magnetCol.rotate_from_angax(angles, axis='z', anchor=(10, 0, 8), start=0)

magnet = magpy.magnet.Cylinder(magnetization=(1200, 0, 0), dimension=(16, 6), position=(0, 0, 8))

magnet.rotate_from_angax(angles, axis='x', start=0)
magnet.rotate_from_angax(angles, axis='z', anchor=(10, 0, 8), start=0)

magpy.show(magnet, magnetCol, backend='plotly', animation=True)
```

### Additional context

OS: Windows 10 64bit
IDE: PyCharm

**Comment by Alexboiboi** [comment]
Hi @9Volts9er,

Thank you for taking the time for reporting this issue ;)

I think the provided example is not a bug, but side effect of the `Collection` philosophy. When creating a `Collection` , an internal position of (0,0,0) is set. The objects added to the `Collection`  do not change this value. Afterwards, when applying a rotation without specifying an anchor, the object's position is taken by default, which is (0,0,0) in your case.

By specifying the position of the `Collection` at initialization, you get the expected result
```python
magnetCol = magpy.Collection(magnet1, magnet2, position=(0,0,8))
```

@OrtnerMichael Any thought on this? I don't really see a way to avoid this kind of confusion without breaking the philosophy of the object positioning. We could set the barycenter of the children`s positions at the instance initialization but this will get messy when paths are already applied on the children beforehand, or if you add children after initialization... I am open for suggestions, but I think we spent a large amount of time thinking about this already^^

**Comment by OrtnerMichael** [comment]
Hi @9Volts9er  and @Alexboiboi 

**Solution**
There are two rotations:

```
xxx.rotate_from_angax(angles, axis='x', start=0)
xxx.rotate_from_angax(angles, axis='z', anchor=(10, 0, 8), start=0)
```

In the first rotation you do not provide an anchor, so the object position is used as anchor. 
- Case1: You rotate the Collection object, so `magnetCol.position` is used as anchor.
- Case2: You rotate the magnet, so `magnet.position` is used as anchor.

You'll notice that those are not the same.

**What is the reason for this ?**

We have given this a lot of thought and finally descided for verision 3++ that Collections are not just simple list-like containers, but objects with their own position and orientation attributes. We think of Collections spanning their own reference frame that can be moved around - and objects in the Collection move with the reference frame.

This kind of thinking enables us to do things as described in the Helmholtz example

**Comment by 9Volts9er** [comment]
Hi @Alexboiboi and @OrtnerMichael,

thank you very much for the detailed explanation. I agree that it could get very messy to calculate the barycenter and set the collections position to this point. But set the position of the collection at initialization is a very good solution, I was not aware that this could be done.

Of course I can review the documentation when it's complete. Just let me know when this is the case.

Thanks a lot for helping me understand this better. Should I close the issue or leave it open until the documentation is ready?

**Comment by OrtnerMichael** [comment]
Thanks for the offer @9Volts9er
This task was moved to #580 .
I will refer to you from there when this is completed.
