### ISSUE TITLE
Potential bug related to missing color in colortable when using Pyvista backend

### ISSUE THREAD

**Issue by peter-leitner** [magpylib/magpylib#590]
### Magpylib version

4.x (Latest)

### What happened?

It seems that a magpylib (v4.0.0) 3D object gets internally assigned a certain color. When trying to plot the object using the Pyvista backend, this color seems to be (no longer?) available. 

The only workaround for the time being seems to me  to define the 3D object instead directly in Pyvista but this is not ideal.

Maybe this issue is due to an incompatibility of the magpylib 4.0.0 version with Pyvista 0.38.2 versions?

<img width="732" alt="errormessage" src="https://user-images.githubusercontent.com/51168238/220151770-bc878521-9bcf-4e5a-90c5-fc1c3f51640d.png">

Minimal example please see below. 

### Code example

```Python
import numpy as np
import magpylib as magpy
from magpylib.graphics import model3d
import pyvista as pv

trace_pyramid = model3d.make_Pyramid(
    base=30, # number of polygons building the base
    diameter=284,
    height=569,
    position=(0,0,569/2),
)

obj1 = magpy.Sensor(style_model3d_showdefault=False, style_label='Pyramid')
obj1.style.model3d.add_trace(trace_pyramid)
# Just want to plot a simple cone, however....
magpy.show(obj1, backend='pyvista')
```

### Additional context

OS: Windows (unfortunately...)
IDE: Spyder

**Comment by Alexboiboi** [comment]
Hi @peter-leitner,

I cannot reproduce the bug with pyvista v0.38.2, which version are you using?

**Comment by peter-leitner** [comment]
Hello @Alexboiboi,

I am using: 
magpylib                  4.0.0                    pypi_0    pypi
pyvista                   0.38.2             pyhd8ed1ab_0    conda-forge

This is weird. I just tried to simply plot a magnet:
```
magnet1 = magpy.magnet.Cuboid(
    magnetization=(0,0,1000),
    dimension=(3,3,6),
    position=(0,0,0)
)
magpy.show(magnet1, backend='pyvista')
```
And again, I get this color-related error when trying to plot the pyvista scene. Could it be that there is an inconsistency when magpylib seems to be installed from pypi and pyvista from conda-forge?

**Comment by Alexboiboi** [comment]
It is not possible that you have magpylib 4.0.0 installed, otherwise you could not use the pyvista plotting backend, which was introduced in 4.1.0
Please check again?
Also, are you using a conda environment?

**Comment by peter-leitner** [comment]
conda -list showed that my environment has magpylib 4.0.0:
<img width="415" alt="1" src="https://user-images.githubusercontent.com/51168238/220385508-3d190fbe-590f-4e0f-9308-9303412165ac.png">
However, when I entered conda install magpylib=4.2.0 it seems I had already 4.1.1, which I don't understand:
<img width="464" alt="2" src="https://user-images.githubusercontent.com/51168238/220385786-1093865b-03ba-44d1-ac8c-f4e63972a04b.png">
Now I updated to the latest magpylib and pip freeze gives:
<img width="496" alt="3" src="https://user-images.githubusercontent.com/51168238/220386040-ddbec508-d9a8-456d-a847-85c9f7483cad.PNG">
When running my minimal example in this very python environment, I still get the color error:
<img width="714" alt="4" src="https://user-images.githubusercontent.com/51168238/220386507-2844111a-64f7-4c9c-80eb-37d57df21316.png">

**Comment by Alexboiboi** [comment]
I have created a fresh environment with magpylib=4.2.0 pyvista=0.38.2 and it runs just fine for me (I am on Mac OS). Maybe you can try this yourself in a clean environment. Sorry that I cannot really help futher, but to me it is not a bug related to magpylib.

 ```bash
conda create --name testenv_py39_magpy_pyvista_bug python=3.9 magpylib=4.2.0 pyvista=0.38.2 --channel conda-forge -y
```

**Comment by peter-leitner** [comment]
Thanks a lot for the suggestion and your time!!

You are right, if it is working properly in your env, it is probably not a bug. When I create a fresh env the way you suggested above, I cannot even import pyvista anymore. Something's screwed up here, but very probably not magpylib related.

**Comment by Alexboiboi** [comment]
> ```shell
> conda create --name testenv_py39_magpy_pyvista_bug python=3.9 magpylib=4.2.0 pyvista=0.38.2 --channel conda-forge -y
> ```

I also tried it in a windows environment and it works fine. 

I know there are some conflicts with pip, anaconda, spyder. Maybe try to reinstall anaconda.
