### ISSUE TITLE
typo in doc content of magpy.show()

### ISSUE THREAD

**Issue by yangyichu** [magpylib/magpylib#592]
### Magpylib version

4.x (Latest)

### What happened?

https://magpylib.readthedocs.io/en/latest/_autogen/magpylib.html?highlight=magpy.show(#magpylib.show
last parameter description: **canvas – If True, the function call returns the figure object. which should be return_fig**

**Comment by Alexboiboi** [comment]
Hi @yangyichu,

We already noticed this typo but thanks anyway for letting us know ;) User feedback is always welcome!

This will be fixed in the upcoming 4.3 release soon.
