### ISSUE TITLE
Review Classes naming

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#603]
Since we always try to have explicit names for all our objects. I think it would make sense to review the current api. 

For the `current.Line`, it would make it clearer when called `current.PolyLine` from the name that the user can generate multiple segments. This may avoid some people unnecessarily creating many `Line` objects.

*Renaming Proposals:*
- Magnets:
  - [x] `Cuboid` -> ok
  - [x] `Cylinder` -> ok
  - [x] `Sphere` -> ok
  - [x] `CylinderSegment` -> ok
  - [x] `Tetrahedron` -> ok
  - [x] `TriangularMesh` -> ok
 - Currents:
   - [x] `Line` -> `Polyline`
   - [x] `Loop` -> `Circle`
- Misc:
  - [x] `Dipole` -> ok
  - [x] `CustomSource` -> ok
  - [x] `Triangle` -> ok
 - Others:
   - [x] `Sensor` -> ok 
 
I would suggest to issue a `DeprecationWarning` for when the old name is used, while still allowing it to avoid breaking changes. We can then remove them when v5 is released (or later).

@OrtnerMichael, What do you think ?

**Comment by OrtnerMichael** [comment]
Hmm ... not sure ...

There a bunch of such "inconsitencies" ... like Loop should be `CircularLoop` and Cylinder the same and `CylinderSegment` should be `CylindricalRingAxialSection` ...

**Comment by OrtnerMichael** [comment]
I like it short and descriptive :)

**Comment by Alexboiboi** [comment]
I think `Ring` is not better since this refers more to an `Annulus`. I would vote for just `Circle`

**Comment by Alexboiboi** [comment]
@OrtnerMichael What is the status about this ?

**Comment by OrtnerMichael** [comment]
Let's do it !!!

`Polyline` and deprecation warning !

**Comment by Alexboiboi** [comment]
Lets review all the names before making any new changes

**Comment by OrtnerMichael** [comment]
I propose `Polyline`

![image](https://github.com/magpylib/magpylib/assets/47384012/c9b3670c-a12b-4ab9-bad2-0375d06681ea)

**Comment by OrtnerMichael** [comment]
But Wikipedia trys to push PolygonalChain on us :)

![image](https://github.com/magpylib/magpylib/assets/47384012/bf7e3d78-4e61-4b98-bc0a-a0f18542465e)

**Comment by OrtnerMichael** [comment]
I think `Polyline` ... or `PolyLine` ?
and `Circle` ... or `CircularLoop` ? ... mmmhh

difficult to descide ...

**Comment by Alexboiboi** [comment]
what about the core functions names, `current_line_field` and `current_loop_field`. I think we should also change these

**Comment by Alexboiboi** [comment]
I made some opinionated decisions (still not set in stones though ^^), see #690
