### ISSUE TITLE
Add `getM()` and `getJ()` - separate inside/outside checks from core functions

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#608]
Core functions are trimmed to performance, the mask generation for inside-outside-edge checks take a lot of time. In most cases users know whether they are inside or outside. One more use of it is to refactor the code to enable the calculation of `getM` and `getJ`.

- [x] can inside-outside checks be separated from core computation ?
- [x] can they be turned on and off in a practical manner ?
- [x] Add `getM()`
- [x] Add `getJ()`

> [!NOTE]  
> `in_out` is currently an unused option in `magnet_trimesh_field`

### to clarify:

- #703

- `Circle`, `Polyline`, `Triangle`, `Dipole` -> what are `getM` and `getJ` outputs ? 
- `Sphere` -> cannot use a generic `convert_BHMJ` because of `polarization/3` factor. What about this factor when calculating  `getM` and `getJ`

**Comment by OrtnerMichael** [comment]
- moving to #647

**Comment by Alexboiboi** [comment]
Reopening this as not addressed. Can still be tracked in  #647
