### ISSUE TITLE
How to plot the field in a cubic region (10mm*10mm*10mm) by color map generated by coil

### ISSUE THREAD

**Issue by caimingxue** [magpylib/magpylib#629]
### What is your question?

<img width="203" alt="image" src="https://github.com/magpylib/magpylib/assets/45029643/426e7863-2024-4e78-a017-2c914dab63de">

**Comment by OrtnerMichael** [comment]
https://magpylib.readthedocs.io/en/latest/examples/examples_30_coil_field_lines.html#pyvista-streamlines
