### ISSUE TITLE
bunch of issues to check later

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#633]
- [x] problem when compiling compound example locally - the opacity of the ring is not visible (magnets inside cannot be seen)
 - [x] something like `style_name='woot'` doesnt generate a msg "you can only have "a, b, c or d" as it does at many other style levels (addressed in #640)
 - [ ] #641
 - [x] Several classes cannot be descibed if initialized empty: (addressed in #640)
    - [x] `Triangle`
    - [x] `CylinderSegment`
    - [x] `Tetrahedron`

**Comment by Alexboiboi** [comment]
> * [ ]  problem when compiling compound example locally - the opacity of the ring is not visible (magnets inside cannot be seen)

@OrtnerMichael I cannot reproduce the problem, can you retry with the latest docs branch ( I just pulled from main into it)
