### ISSUE TITLE
Is there an option to make absolute arrowhead sizes?

### ISSUE THREAD

**Issue by bibbibob** [magpylib/magpylib#637]
### What is your question?

As far as I can see currently arrow_size makes it a relative size to the arrow length, but I cannot find a way to make a flat arrow size regardless of vector length. Now it is possible to scale it by vector length and solve the problem in that manner, but it would be nice if there was a way to set their sizes in absolute terms to ensure that they were equal.

Apologies if I have overlooked anything!

**Comment by Alexboiboi** [comment]
Hi @bibbibob,
I am assuming you are referring to the arrow of `magpylib.current` objects. In deed there is currently no way to do this, yet but we are considering adding this feature soon.

- Arrow styling properties are currently tracked in #635 and we will probably also implement a sizing `mode` there ;)

Hope it helps,

Alex -

**Comment by bibbibob** [comment]
Ah, alright then, looking forward to it!  
And thank you for your work on the package, it is extremely helpful!

**Comment by Alexboiboi** [comment]
Hi @bibbibob,

I have created a Pull Request regarding this topic, with a visual example. Please comment on it, if it still does not fit your needs ;)
- #639
