### ISSUE TITLE
module 'magpylib' has no attribute 'show_context'

### ISSUE THREAD

**Issue by SoundDesignerToBe** [magpylib/magpylib#645]
### Magpylib version

4.x (Latest)

### What happened?

Hello,

I am working through the Introduction on the [readthedocs](https://magpylib.readthedocs.io/en/latest/_pages/page_01_introduction.html#intro-field-computation). 

I have magpy version 4.3.0 installed with pipenv, on Python 3.11.4, Fedora 38.

The first time the magpy.show_context Context Manager is used, I get an AttributeError with message
module 'magpylib' has no attribute 'show_context'

Can someone help me fix this?

### Code example

```Python
import magpylib as magpy

sensor = magpy.Sensor(pixel=[(0, 0, -0.2), (0, 0, .2)], style_size=1.5)
magnet = magpy.magnet.Cylinder(magnetization=(100, 0, 0), dimension=(1, 2))

with magpy.show_context(magnet, sensor, backend='plotly'):
    pass
```

### Additional context

OS: Fedora 38
Python 3.11.4
installed with pipenv install magpylib
magpylib version 4.3.0

**Comment by Alexboiboi** [comment]
Hi @SoundDesignerToBe, 

thank you for taking the time to describe your problem ;)

The readthedocs link you provided points to the latest Magpylib main branch version and yet to be released.

The newly added `show_context` context manager for coupled subplots is going to be included in the next release (v4.4) very soon. The documentation is still _work in progress_. 

However, if you still want to test this feature you will need to install Magpylib from source:
```bash
pip install git+https://github.com/magpylib/magpylib@main
```

Hope this helps, Alex - 

@OrtnerMichael Maybe we should not let the docs/latest point to the main branch, but instead to the latest release (like before), to avoid this kind of misunderstandings?

**Comment by OrtnerMichael** [comment]
Agreed.

Was not even aware that `show_context` is already documented :).

**Comment by SoundDesignerToBe** [comment]
Hi Alex,

thank you for the quick reply and the help. It is indeed a bit confusing as it displays 4.3.0 in left upper corner when it points somewhere else. 

I intended to install within my pipenv environment to make this work. 
I tried different install command variations, but I kept getting the error when executing the script from my initial question. 

Within the active environment:
- `pip install git+https://github.com/magpylib/magpylib@main` reports no errors
- `pipenv run pip install git+https://github.com/magpylib/magpylib@main` reports no errors
- `pipenv install git+https://github.com/magpylib/magpylib@main` fails asking for a `#egg` specification

I hoped to have found a [solution](https://stackoverflow.com/questions/51201515/pipenv-requires-an-egg-fragment-for-version-controlled-dependencies-warning-w), but running
- `pipenv install git+https://github.com/magpylib/magpylib#egg=magpylib`
... executed successfully, but the issue remained. 

- `pipenv install git+https://github.com/magpylib/magpylib#egg=magpylib@main`
raises an InstallationError, Invalid requirement: 'magpylib@main'. 

I fixed this the quick and dirty way now, by setting up a new environment with virtualenv instead and used the 'pip install ...' command. This works for me.

**Comment by SoundDesignerToBe** [comment]
Thank you!
