### ISSUE TITLE
Numerical instability of cylinder_segment

### ISSUE THREAD

**Issue by fslanovc** [magpylib/magpylib#648]
### Magpylib version

4.x (Latest)

### What happened?

Unfortunately the cylinder segment formula is highly unstable, so it might happen that the special cases are not handled properly.

Until this is fixed on the implementation side, I suggest to increase the tolerance in line 42 in field_BH_cylinder_segment.py from 1e-14 for instance to 1e-12. This should lead to maybe a slightly lower accuracy in some cases, but you don't get NaN as output so easily. In my case, this fixed already the issue.

**Comment by OrtnerMichael** [comment]
hi @fslanovc 

Thank you for pointing this out. Can you make a pull request to fix the problem as you proposed ?
is 1e-12 a good value ? could also be 1e-10 ?

- does this also solve #606 ?

mfg
