### ISSUE TITLE
Question concerning show_context

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#656]
When I have a sensor with multiple pixel `show_context` displays the mean - should we really have `pixel_agg="mean"` by default here ?

**Comment by Alexboiboi** [comment]
We main goal with the 2D field plots is to have a quick look at the field values over a path, that is why we have the `"mean"` aggregation. This prevents also to blow up the plots immediately, if the user has many pixels. For the same reason the `sumup=True` by default to limit the number of sources.

**Comment by OrtnerMichael** [comment]
I understand, I'm not strongly opposed to the idea ... but an unsuspecting user who is not aware of of the `sumup` or the `pixel_agg` arguments might be quite confused ...

ok ... you have conviced me :) let's leave it as it is !!! ... for now
