### ISSUE TITLE
Legend color issue

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#661]
several issues described below:
- [x] Matplotlib legend colors are too dark
- [ ] Pyvista sometimes has only black color in legend
- [ ] Pyvista legend fontsize strangely changes from figure to figure

-------------------------------

In this program:

```python
import magpylib as magpy

dips = [
    magpy.misc.Dipole(
        moment=(0, 0, 1),
        position=(size, 0 if sizemode == "scaled" else 1, 0),
        style_size=size,
        style_sizemode=sizemode,
        style_pivot="tail",
        style_label=f"{sizemode=}, {size=}",
        style_description_show=False,
    )
    for size in range(1, 4)
    for sizemode in ("scaled", "absolute")
]
magpy.show(*dips, backend='matplotlib')
```

Matplotlib Legend colors look strangely dark:

![image](https://github.com/magpylib/magpylib/assets/47384012/2f9d8c57-590d-4dbe-b75c-ded200466a5f)

Pyvista and Plotly look good

--------------------------

In this program:

```python
import magpylib as magpy

sens = [
    magpy.Sensor(
        position=(size - 3, 0 if sizemode == "scaled" else 2, 0),
        style_size=size,
        style_sizemode=sizemode,
        style_label=f"{sizemode=}, {size=}",
        style_description_show=False,
    )
    for size in range(1, 4)
    for sizemode in ("scaled", "absolute")
]
magpy.show(*sens, backend='pyvista')
```

Pyvista has no colors. 

![image](https://github.com/magpylib/magpylib/assets/47384012/b5a9ac3a-dfbb-4c47-bf62-b5cc51de5ad0)

Matplotlib is strangely dark.
Plotly is good.

------------------------------

In this program

```python
import magpylib as magpy
import numpy as np

sens = [
    magpy.Sensor(
        pixel=[(0, 0, 0), (1, 0, 0), (2, 0, 0)],
        position=(0, 0 if pixel_sizemode == "scaled" else 1, 0),
        style_pixel_size=0.5,
        style_pixel_sizemode=pixel_sizemode,
        style_label=f"{pixel_sizemode=}, pixel_size=0.5",
        style_description_show=False,
    )
    for pixel_sizemode in ("scaled", "absolute")
]
magpy.show(*sens)
```

Pyvista is again just black

![image](https://github.com/magpylib/magpylib/assets/47384012/12739a92-65c1-484b-a68a-cfe5ec12c123)

Matplotlib is dark and Plotly is good.

also in the last example the Pyvista legend fontsize is extremely small ... why does it change from plot to plot ? is it set as absolute ?

**Comment by Alexboiboi** [comment]
### Matplotlib legend is too dark

The legend box is generated automatically by matplotlib. Even if there is the possibility to change it manually via a Custom Legend Handler (with some effort), is it worth it? For multicolored magnets, could be nice though (like for plotly).

### Pyvista legend has no colors
Generic mesh traces dispatched to the backends have either a single `color` argument or  a `facecolor` argument in form of a list. If it is a single color, it is recognized by Pyvista in the legend. If `facecolor` is present, the cell colors are passed to the  `cell_data` attribute of a pyvista mesh object. These colors don't reflect in the legend and there is no way around it.

### Pyvista legend font is small
I didn't find anywhere how to control this setting
