### ISSUE TITLE
Handedness

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [magpylib/magpylib#676]
Is it possible to change the handedness of a sensor coordinate system? 
I didn't find anything in the manual and it cannot be done by rotation alone. 

I know I can do something like the snippet below, but it is confusing that the scene picture is wrong then. 
```python
def calc_field(sensors):
    # compute field at sensor
    sensors_B = []
    for sensor in sensors:
        B_tmp = sensor.getB(magnet, sumup=True)
        B_tmp[:,2] = (-1)*B_tmp[:,2]  # flip sensor / not possible with rotation
        sensors_B.append(B_tmp)

    return sensors_B
```

**Comment by OrtnerMichael** [comment]
hi @Nikolai-Hlubek,
Sorry for the late reply.

The handedness of the sensor coordinate system is not implemented. But you can easily change your calculation to give the results for a left-handed sensor.

First you have to define in which directions the LH sensor axes should point with respect to the RH sensor that is implemented.
One easy choice is (x,y,z) -> (x,-y,z). In this case the y-axis of the LH sensor simply points into the -y direction of the RH sensor. The computation is achieved by multiplying the output from `getB` with (1,-1,1).

```
getB_LH = getB(...) * np.array((1,-1,1))
```

There is also a fancy way to generate a native magpylib sensor with left-handed system by subclassing the `Sensor` class and returning `getB` as described before. The approach is similar to what we show [here](https://magpylib.readthedocs.io/en/latest/_pages/gallery/gallery_tutorial_custom.html#gallery-tutorial-custom).

Is this what you are looking for?

sincerely,
michael

**Comment by Nikolai-Hlubek** [comment]
Hi Michael

Thank you for the reply. I didn't know that it is not implemented. 
Than you can regard my question as a feature request instead. 

How to change handedness in the result I know - I had some code for this in the question. However, this still means that magpy.show() shows the wrong sensor orientation, which is confusing, if I show the scene to colleagues to discuss results. 

magpylib is really an awesome product.

Best wishes
Nikolai

**Comment by OrtnerMichael** [comment]
hi Nikolai,
Thank you for the praise :).
I understand the problem and we will discuss about a possible implementation and keep this issue open as feature request

Can you give us some context/motivation? Is this for a real sensor? I was under the impression that most sensors should have a right handed coordinate system implemented?

**Comment by Nikolai-Hlubek** [comment]
Hi Michael

The use case is as follows: 
I'm developing an embedded position sensor. I used to use a hand-coded analytical formula for the magnetic field before I discovered magpylib. I'm using magpylib inside Jupyter notebooks. I setup a scene with magnets and sensors. Then I put this scene through an optimizer to get ideal positions of sensors and magnets. Based on the results I get, some colleagues do experiments with a real setup. Most important are of course the results of the field simulations of magpylib and they are correct. However, when checking the input of my simulations or discussing the results of the simulations to figure out, how to set up the experiments `magpylib.show()` has been really helpful. What has always been confusing is, when magpylib.show() showed the sensors orientation in another way than what was used in my simulations, because I adjusted the output of `get_B()`. So it was always required to generate a separate presentation with custom pictures to explain simulation and result. If `magpylib.show()` would support handedness I could directly use the jupyter notebook as basis for the discussion with colleagues. 

As for embedded multi-axis sensors there seems to be no industry standard regarding the handedness. 

Infineon uses a left handed coordinate system. 
![image](https://github.com/magpylib/magpylib/assets/7396434/0350f1af-db55-4cdc-bc56-fc5c5eee48a0)

TI uses a right handed coordinage system. 
![image](https://github.com/magpylib/magpylib/assets/7396434/ab22c5e7-b246-4742-b8cb-98021b2a44bc)

Allegro uses a left handed coordinate system. 
![image](https://github.com/magpylib/magpylib/assets/7396434/d654757d-2083-4a01-99f4-39d663c4aee4)

An all manufacturers having the coordinate system with regard to their chip orientation differently.

**Comment by Alexboiboi** [comment]
Hi @Nikolai-Hlubek,

Not sure yet if we would implement a new Left-Handed-Sensor class or just add an argument to the current Sensor class but in the meantime you could use a custom Sensor subclass as shown below. Note that the graphical representation makes use of plotly and is not very efficient.

> [!WARNING]
> The following code will result in bad axis actually flipped because of a bug I just found when writing this example (see #679). Until we merge the PR and make a patch release in the next days, you can use the [bugfix branch](https://github.com/magpylib/magpylib/tree/bugfix/sensor-arrows-show) if you want to have the correct arrow orientations.

```python
import magpylib as magpy


class SensorFlippable(magpy.Sensor):
    _allowed_axes = set("xyz")

    def __init__(self, flipped_axes="z", **kwargs):
        super().__init__(**kwargs)
        self.flipped_axes = flipped_axes
        self.style.sizemode = "absolute"  # model3d does not scale otherwise
        self.style.model3d.add_trace(self._custom_trace3d)

    @property
    def flipped_axes(self):
        return self._flipped_axes

    @flipped_axes.setter
    def flipped_axes(self, val):
        val = set(val)
        if val - self._allowed_axes:
            raise ValueError(f"Flipped axis must be in {self._allowed_axes}")
        self.style.arrows.update(**{f"{k}_show": k not in val for k in "xyz"})
        self._flipped_axes = val

    def _custom_trace3d(self):
        ax = self.flipped_axes
        style = self.style.as_dict(flatten=True, separator="_")
        style = {k: v for k, v in style.items() if "model3d" not in k}
        s = magpy.Sensor(style=style)
        for k in ax:
            s.rotate_from_angax(180, "z" if k != "z" else "x")
        s.style.arrows.update(**{f"{k}_show": k in ax for k in "xyz"})
        fig = s.show(return_fig=True, backend="plotly")
        kwargs = fig.data[0].to_plotly_json()
        kwargs["showlegend"] = False  # comment out if legend for flipped axes
        suff = f"{[*ax][0]}-axis" if len(ax) == 1 else f"{''.join(ax)}-axes"
        kwargs["name"] = f"{self.__class__.__name__} flipped {suff}"
        return {"constructor": "Mesh3d", "kwargs": kwargs}

    def _getBH_flipped(self, field, *sources, **kwargs):
        fn = getattr(self, f"get{field}")
        bh = fn(*sources, **kwargs)

        output = kwargs.get("output", "ndarray")
        for ax in self.flipped_axes:
            if output == "dataframe":
                bh[f"{field}{ax}"] *= -1
            else:
                ind = list("xyz").index(ax)
                bh[..., ind] *= -1
        return bh

    def getB_flipped(self, *sources, **kwargs):
        return self._getBH_flipped("B", *sources, **kwargs)

    def getH_flipped(self, *sources, **kwargs):
        return self._getBH_flipped("H", *sources, **kwargs)
```

And you can use it as
```python
sl = SensorFlippable(flipped_axes="x")
sl.rotate_from_angax(30, "y", anchor=(2, 4, 2))
cyl = magpy.magnet.Cylinder((1, 1, 1), (1, 1), position=(1, 0, 0))
magpy.show(sl, cyl)
```

<img width="366" alt="image" src="https://github.com/magpylib/magpylib/assets/29252289/e40a211e-d1e8-4a19-91d5-a7d59b15e8e8">

```python
import pandas as pd

df_list = []
for f in ("", "x", "y", "z", "xy"):
    s = SensorFlippable(flipped_axes=f)
    # print(s.getB(c))
    df = s.getB_flipped(cyl, output="dataframe")
    df["flipped at"] = f
    df_list.append(df)
pd.concat(df_list)
```

Hope this also helps - Alex

<img width="871" alt="image" src="https://github.com/magpylib/magpylib/assets/29252289/e759fc44-d618-4565-be69-3ce9ec1e51f7">

**Comment by OrtnerMichael** [comment]
@Nikolai-Hlubek 

Thank you for the info! Didn't know the Allegro sensor is also left-handed :).

Also, the way you describe it is exactly how we intended Magpylib to be used! 🥇 


sincerely,
Michael

**Comment by Alexboiboi** [comment]
Hi @Nikolai-Hlubek,

A patch has been released (v4.1.1) which solves the issue mentioned above. The example code I wrote above should work properly with this version.

BR, Alex

**Comment by Nikolai-Hlubek** [comment]
Thank you very much, for your help guys and thank you for pushing the patch forward.

**Comment by OrtnerMichael** [comment]
@Alexboiboi to me the handedness makes a lot of sense based on contemporary sensor coordinate choices. Shall we add this feature in a 4.2 version ?

**Comment by Nikolai-Hlubek** [comment]
When I wrote my initial question I was checking for a handedness kwarg and did not find any. 
So a kwarg seems natural to me. 

As for the exact wording, I'm no native English speaker and don't know what the most commonly used term is. 
Both 
- `handedness='right'`
- `right_handed=True`
seem obvious. Is the boolean better from a performance or ressources point of view? 

As for defaults, I would leave them as they are so not to break existing code.

**Comment by OrtnerMichael** [comment]
Makes sense to me.

What about the default orientation with respect to the RHS? There are many ways to define a respective LHS.

I suggest xyz -> yxz ... this seems most natural to me

**Comment by Alexboiboi** [comment]
Hi @Nikolai-Hlubek, @OrtnerMichael,

I just created a Pull Request (#687) addressing this feature-request. Please take the time to review and comment it !

Thanks
