### ISSUE TITLE
`Sensor` class argument position is inconsistent - `position` should not be before `pixel` and `handedness`

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#699]
`Sensor` class argument position is inconsistent - `position` should not be before `pixel` and `handedness`

- [ ] use `__init__(*, ...)` to avoid silent breaking changes?

**Comment by OrtnerMichael** [comment]
- no we agreed on keeping positionals
- also on rearranging argument orders as described in #698

**Comment by Alexboiboi** [comment]
fixed by #712
