### ISSUE TITLE
Update conda-forge feedstock for Anaconda 

### ISSUE THREAD

**Issue by lucasgcb** [magpylib/magpylib#700]
Hi, guys! Congrats on the latest release and the CI upgrade with GitHub Actions :)

It seems that our continuous delivery to [Anaconda](https://anaconda.org/conda-forge/magpylib) needs some adjustment due to this, so as of now `conda` users won't be getting the latest releases and are stuck on version `4.4.1`. I'm making this issue to track this.

As of now, our automerge for the feedstock is failing:
https://github.com/conda-forge/magpylib-feedstock/pull/26

I'll be taking a look over the course of the week and reach out to the conda-forge guys to get the continuous deployment back up.

**Comment by Alexboiboi** [comment]
Hi @lucasgcb, thanks for taking care of this! 
Maybe worth to check some github actions for publishing to conda, but it looks like it is not really an established workflow...

**Comment by OrtnerMichael** [comment]
Hey Lucas! thanx 1b for taking care of this! 🥇

**Comment by lucasgcb** [comment]
Should be [back on track](https://anaconda.org/conda-forge/magpylib) from here on out!
Tested on Anaconda Linux and worked fine on their Jupyter Lab with the graphical backends :)
It'd be cool if someone else could also confirm the Anaconda distribution is fine, otherwise this issue is concluded.

- Only thing that needed changing was [the requirements section](https://github.com/conda-forge/magpylib-feedstock/commit/40a6cd0388c6eeddfacadf6e322a606ebd479902#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aL19-R27) in the conda build recipe to include new requirements 
  - `flit-core` is [a new build dependency](https://github.com/magpylib/magpylib/commit/e9475ae34a5030e7e1e74afaf67bf6549680c755#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R2) added alongside the pyproject.toml in our recent CI Upgrade. 

Whenever a new build requirement is added (toolchains, build backends, etc), [the recipe on our "feedstock"](https://github.com/conda-forge/magpylib-feedstock/blob/40a6cd0388c6eeddfacadf6e322a606ebd479902/recipe/meta.yaml#L18-L21) must be manually updated so conda-forge can build the package for Anaconda.


We could also take a look at tweaking the description and other things if there's need, but that's a different issue.

---

> Hi @lucasgcb, thanks for taking care of this! Maybe worth to check some github actions for publishing to conda, but it looks like it is not really an established workflow...

@Alexboiboi They do seem to use GitHub actions for some things, however the actual pushing to Anaconda is done with their own bots for whatever reason. Our conda release is powered by [conda-forge](https://conda-forge.org/) channel so they have the authority over the pipelines and delivery for the most part; we just worry about PyPi and build instructions.

In the future we _could_ make our own channel if need be, but it's nice to have their consolidated community support.

**Comment by OrtnerMichael** [comment]
cool thanx 1b! im closing this then :) - v4.5 is available from conda-forge
![image](https://github.com/magpylib/magpylib/assets/47384012/d0f65e0c-99d3-4a9a-9d50-dde952713d92)
