### ISSUE TITLE
Add Migration guide v4 -> v5 to docs 

### ISSUE THREAD

**Issue by Alexboiboi** [magpylib/magpylib#709]
Since v5 breaks a lot of v4 code it may make sense to have a small dedicated guide for user to migrate from v4 to v5.

**Comment by OrtnerMichael** [comment]
@Alexboiboi thats the changelog no? :)
do we really need a migration guide?
where would you put it?

**Comment by OrtnerMichael** [comment]
let's not do this one - we have such a nice changelog
