### ISSUE TITLE
Axial Flux Generator Simulation using Dataframe

### ISSUE THREAD

**Issue by flashGee** [magpylib/magpylib#713]
### Axial Flux Generator Simulation

I've been working on a Jupyter Notebook project to illustrate considerations for an axial flux generator. For this purpose, I've utilized Magpylib. The project features an interactive ipywidget to demonstrate the concept, followed by a streamplot visualization and an animation showcasing the qualitative properties of the generator.

Both the streamplot and the magpy.show context manager appear to yield similar results in terms of the magnetic field representation. However, I've encountered an issue where the DataFrame and I am looking for guidance on how to address it.

The complete code for this project is hosted on GitLab. Any insights or suggestions on how to reconcile these differences in the magnetic field values would be greatly appreciated.

Thank you for your support.

https://gitlab.com/flash.g/urban-vawt/-/tree/main/afpm-gen?ref_type=heads

Edited 07012024: changed repo / added stuff

**Comment by Alexboiboi** [comment]
Hi @flashGee, 

Happy new year, and sorry for the late reply!

As I see from your notebook, you calculate the magnetic flux in 3 different ways:

1. For streamlines plot:
```python
# Calculate the magnetic field B on the meshgrid
B_field = collection.getB(observers)
```
In this case, when `getB` (or `getH`) is called from a `Collection` it returns the sum of all sources, as it is considered as a single source.

2. For `show` or `show_context`
```python
with magpy.show_context(*magnets, sensor1 , sensor2, sensor3 , sensor4, sensor5, sensor6 ,animation=True, backend="plotly", style_pixel_size=0.2):
    magpy.show(col=1)
    magpy.show(output='Bx', col=2, pixel_agg=None) # `sumup=True` by default
``` 
There the field values are also aggregated for all sources by default. If you don't want this behavior add `sumup=False` to the `show` call.

3. For `getB` with a list of sources
```python
# Calculate magnetic field data and store in a DataFrame
B = magpy.getB(
    magnets,  # List of magnets
    [sensor1, sensor2],  # List of sensors
    output='dataframe',  # Output format as DataFrame
    sumup=True,
)
```
Here the `sources` parameter provided is a list of sources (`magnets` in your script) and not a `Collection` so `getB` returns the field values for each combination of sources and sensors. If you want the same behavior as for the `Collection` you need to add the `sumup=True` argument to the `getB`  call.

Hope this helps and if you need more help feel free to ask more specific details.

Best regards, Alex

> WARNING
> Version 5 is around the corner and comes with major breaking changes, among which the switch to SI units. If you plan to use this script later again, make sure to pin down the magpylib version <5 until you are ready to migrate  (see details -> #647)

**Comment by flashGee** [comment]
Hey @Alexboiboi ,
thx for your answer. Your soulution worked very well for my issue.

`# Calculate magnetic field data and store in a DataFrame
B = magpy.getB(
    magnets,  # List of magnets
    [sensor1, sensor2],  # List of sensors
    output='dataframe',  # Output format as DataFrame
    sumup='True',
)`

It was my intention to use the 3 different ways to calculate the magnetic flux and reproduce the same results. 

`print(magpy.__version__)`

I used version 4.5.0 for this. Thx for our work with magpylib.  I am looking forward to check out 5.0

Many thx.

I close this issue now?

**Comment by Alexboiboi** [comment]
Happy to help ;) 

Closing this now
