### ISSUE TITLE
add mu0 at top level

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#714]
lets add the constant MU0 at the top level ?

```
import magpylib as magpy

magpy.mu0

or

magpy.MU0
```
?

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael,

Scipy actually uses `mu_0`, and since it is already a mandatory dependency to Magpylib I wonder if we want to have it on the Magpylib side also.

https://docs.scipy.org/doc/scipy/reference/constants.html#physical-constants

```python
import scipy
scipy.constants.mu_0 # -> 1.25663706212e-06
```

**Comment by OrtnerMichael** [comment]
yes we do :)

`magpy.mu_0` ?

I would really prefer `mu0` ... but I guess we should stick to conventions :(

**Comment by OrtnerMichael** [comment]
Also, we should change from our internal mu0=4 pi 1e-7 to scipy.constants.mu_0 because since 2019 mu0 is not anymore 4pi 1e-7 but an experimental value close to this number when e-charge and plank constant were fixed.

**Comment by OrtnerMichael** [comment]
WIP in #717

**Comment by OrtnerMichael** [comment]
completed in #717
