### ISSUE TITLE
Change to `style_magnetization_mode="arrow"` in matplotlib by default

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#735]
its really annoying that i alwys have to write this when i develop things because of the terrible matpltolib 3d vizualization

**Comment by Alexboiboi** [comment]
you'd like `"arrow"` or `"arrow+color"` ?

**Comment by OrtnerMichael** [comment]
just arrow, like it was before ... i know this creates a difference between
default matplotlib and default others ... but matplotlib graphis are just
really crappy

Alexandre Boisselet ***@***.***> schrieb am Fr., 1. März
2024, 16:00:
