### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#748]
Hi @Alexboiboi 

When I want to change the trace of an object using `add_trace()` in the following way

```python
import magpylib as magpy

trace = magpy.graphics.model3d.make_Prism()
cube = magpy.Sensor().style.model3d.add_trace(trace)
```

then `type(cube)` is `Model3d`, for obvious reasons.

Is this normal behavior ? Somehow I felt that this should work in the same way as

```python
import magpylib as magpy

trace = magpy.graphics.model3d.make_Prism()
cube = magpy.Sensor()
cube.style.model3d.add_trace(trace)
```

can you please comment on this?

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael,

I don't see any problem here and I don't understand your confusion. The two code blocks do basically the same. Just what you assign to cube differs.
When you use the dot notation after `x = magpy.Sensor().whatever`, then  `x` will be assigned `whatever` and if `whatever` is a method call then `x` will be whatever the method returns.

**Comment by OrtnerMichael** [comment]
the point is that i want to chain my sensor object, sensor.dox().doy().doz() but .add_trace() does not return the sensor but the model3d so that sensor now points at model3d, not the Sensor object.

so while one would think that the two code blocks do the same, the first one is actually completely wrong and useless.

this is what i mean. it feels like it should do one thing, but its doing another thing :)

**Comment by Alexboiboi** [comment]
can we close this?
