### ISSUE TITLE
Potentially inaccurate year in citation in documentation and code

### ISSUE THREAD

**Issue by feldnerd** [magpylib/magpylib#761]
### Magpylib version

5.x (Latest)

### What happened?

The documentation and code cite Yang1999. If this refers to the following [paper](https://iopscience.iop.org/article/10.1088/0953-2048/3/12/004), then the year should be **1990**, not **1999**.

**Comment by Alexboiboi** [comment]
Hi @feldnerd,

Thanks for pointing this out, would you like to submit a pull request to fix this ? 

Just follow this link:
https://github.com/magpylib/magpylib/edit/main/docs/_pages/docu/docu_physics.md

**Comment by OrtnerMichael** [comment]
hi @ feldnerd - yes you are right! Thanks for pointing this out.
br michael

**Comment by feldnerd** [comment]
Hi @OrtnerMichael and @Alexboiboi happy to try the pull request, here it is: https://github.com/magpylib/magpylib/pull/764

This additionally updates the citation in the field_BH_cuboid file.

**Comment by OrtnerMichael** [comment]
this was fixed in #764, thanx @feldnerd
