### ISSUE TITLE
docs minifix

### ISSUE THREAD

**Issue by OrtnerMichael** [magpylib/magpylib#770]
A memory efficient way to create a grid with numpy by broadcasting into an allocated array - no respective creation of `X` and `Y` grids as in the docs example  [here](https://magpylib.readthedocs.io/en/latest/_pages/gallery/gallery_vis_mpl_streamplot.html#gallery-vis-mpl-streamplot)

```python
grid = np.zeros((100,100,3))
grid[:,:,(0,2)] = np.mgrid[-1:1:100j, -1:1:100j].transpose((2, 1, 0))
```

**Comment by Alexboiboi** [comment]
Hi Michael,

I don't see much benefit in terms of memory here, especially with the B-field computation coming afterwards.

BTW I fixed the code in your comment above to make it work (you had 101 instead of 100 in `np.zeros(...`

**Comment by Alexboiboi** [comment]
You can also make it a one-liner:
```python
grid = np.mgrid[-1:1:100j, 0:0:1j, -1:1:100j].T[:,0]
```

**Comment by OrtnerMichael** [comment]
this is very nice !
