### ISSUE TITLE
Very minor oddity/bug with show function when showing single straight line current

### ISSUE THREAD

**Issue by bibbibob** [magpylib/magpylib#771]
### Magpylib version

5.x (Latest)

### What happened?

I tried to run a simple test on just a wire using the following code, but the show function fails to zoom properly.

A = 90e-3
u=1e-3
w0 = magpy.current.Polyline(current=A,vertices=((0.0025,0.0025,-u/2),(0.0025,0.0025,u/2)),position=(0,0,0))
magpy.show(w0)

The show function is zoomed out in a 1m x 1m x 1m box which shows nothing. 

If you alter the line a bit to have a tilt to one side however, eg changes position from 0.25 to 0.24 one place, the show function works again.

w0 = magpy.current.Polyline(current=A,vertices=((0.0025,0.0025,-u/2),(0.0025,0.0024,u/2)),position=(0,0,0))

Alternatively once you have two currents two different places it also works again, so it most likely is only in the single current case, so really a minor and niche bug.

Just a heads up in case it is not a known issue. Otherwise appologies for spam!

### Code example

```Python
import magpylib as magpy
A = 90e-3
u=1e-3
w0 = magpy.current.Polyline(current=A,vertices=((0.0025,0.0025,-u/2),(0.0025,0.0025,u/2)),position=(0,0,0))
magpy.show(w0)
```

**Comment by OrtnerMichael** [comment]
hey @bibbibob ,

thank you for pointing this out and for your precise description of the problem.

I have also noticed some oddities with how the automatic view-boundaries are chosen since v5 release.

We will fix this shortly!

br michael
