### ISSUE TITLE
Github documentation link links to development version instead of stable

### ISSUE THREAD

**Issue by purepani** [magpylib/magpylib#802]
### Magpylib version

5.x (Latest)

### What happened?

Currently the link on the sidebar of the github page links to the development version([magpylib.readthedocs.io/en/latest/](https://magpylib.readthedocs.io/en/latest/)). I expect most users would want to be linked to the stable version: https://magpylib.readthedocs.io/en/stable/

**Comment by OrtnerMichael** [comment]
hey @purepani 

thank you for pointing this out. I also think it is weird this way, but there are other voices in the team who think that it is better this way, showing on-going developments.

The dev version includes all docs improvements, and includes documentation of features that have already been integrated into the main branch, but are not released yet.

br michael

**Comment by purepani** [comment]
That certainly makes sense!
Just thought it might have been an error, but if it's a conscious decision then no need to change it obviously!

**Comment by OrtnerMichael** [comment]
Beiing ignored by @Alexboiboi  I wil just close this then :)
